/********************************************************
*
* Name: DM_PLAZA_INFO_PROC
* Created by: JL, 6/13/2016
* Revision: 1.0
* Description: This is the mapping script for
*              DM_PLAZA_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE SEQUENCE DM_PLAZA_INFO_PLAZA_ID_SEQ
   INCREMENT BY 1
   START WITH 1
   NOMAXVALUE
   NOCYCLE
   CACHE 100;

CREATE OR REPLACE PROCEDURE DM_PLAZA_INFO_PROC IS

TYPE DM_PLAZA_INFO_TYP IS TABLE OF DM_PLAZA_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PLAZA_INFO_tab DM_PLAZA_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    DM_PLAZA_INFO_PLAZA_ID_SEQ.NEXTVAL PLAZA_ID
    ,IAG_PLAZA_ID EXTERN_PLAZA_ID
    ,PLAZA_NAME NAME
    ,'0' ADDRESS_ID
    ,to_date('1/1/1900','MM/DD/YYYY') OPENED_DT
    ,'0' DMQ_PLAZA_MASK
    ,SYSDATE UPDATE_TS
    ,SIA.AGENCY_ID AGENCY_ID
    ,'0' DEFAULT_PLAN_ID
    ,'00:00:00' REVENUE_TIME
    ,'0' COURT_ID
    ,'0' PLAZA_GROUP
    ,'000.000.000.000' IP_ADDRESS
    ,'CCSS' NODENAME
    ,'CCSS' USERNAME
    ,'CCSS' PASSWORD
    ,'N/A' TS_DIR
    ,'N/A' TX_DIR
    ,'N/A' IMAGE_INCOMING_VOLUME
    ,'N/A' IMAGE_ARCHIVE_VOLUME
    ,DECODE(SUBSTR(PLAZA_ID,1,3),'004','C','B') PLAZA_TYPE_IND
    ,'N' END_PLAZA_IND
    ,'N' SECTION_CODE_IND
    ,'0' SECTION_ID
    ,PLAZA_SHORT_NAME PLAZA_ABBR
    ,'0' PLAZA_SEQ_NUMBER
    ,'0' MILEAGE
    ,'0' PLAZA_MASK
    ,'0' HWY_NO
    ,FTE_PLAZA IS_HOME_PLAZA
    ,'0' PORT_NO
    ,'NO' CALCULATE_TOLL_AMOUNT
    ,'N' LPR_ENABLED
    ,NULL GRACE_PERIOD
    ,NULL GRACE_TIME
    ,CTY.COUNTY_CODE_DESC JURISDICTION
    ,'NA' IMAGE_RESOLUTION
    ,FACCODE_FACILITY_CODE FACILITY_ID
    ,'NA' JURISDICTION_CODE
    ,'0' POSTING_TYPE
    ,PLAZA_ID HOST_PLAZA_ID
    ,'SUNPASS' SOURCE_SYSTEM
    ,UTURN_INTERVAL POACHING_LIMIT
FROM PATRON.PA_PLAZA PA,
     PATRON.PA_COUNTY CTY,
     PATRON.ST_INTEROP_AGENCIES SIA
WHERE PA.COUNTY_COUNTY_CODE = CTY.COUNTY_CODE
AND   PA.AUTHCODE_AUTHORITY_CODE = SIA.AUTHORITY_CODE;

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PLAZA_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_PLAZA_INFO_tab.first .. DM_PLAZA_INFO_tab.last
           INSERT INTO DM_PLAZA_INFO VALUES DM_PLAZA_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


