/********************************************************
*
* Name: DM_PA_PLAZA_PROC
* Created by: DT, 4/31/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_PA_PLAZA
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_PA_PLAZA_PROC IS

TYPE DM_PA_PLAZA_TYP IS TABLE OF DM_PA_PLAZA%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PA_PLAZA_tab DM_PA_PLAZA_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    PLAZA_ID PLAZA_ID
    ,ADMINTYPE_ADMIN_TYPE_CODE ADMINTYPE_ADMIN_TYPE_CODE
    ,AUTHCODE_AUTHORITY_CODE AUTHCODE_AUTHORITY_CODE
    ,COUNTY_COUNTY_CODE COUNTY_COUNTY_CODE
    ,FACCODE_FACILITY_CODE FACCODE_FACILITY_CODE
    ,REGCODE_REGION_CODE REGCODE_REGION_CODE
    ,RAMPTYPE_RAMP_TYPE_CODE RAMPTYPE_RAMP_TYPE_CODE
    ,TRUSTEE_TRUSTEE_ID TRUSTEE_TRUSTEE_ID
    ,PLAZA_SHORT_NAME PLAZA_SHORT_NAME
    ,PLAZA_NAME PLAZA_NAME
    ,PLAZA_SLAVE_NUM PLAZA_SLAVE_NUM
    ,NULL MILE_POST
    ,GEOG_COORD_LAT GEOG_COORD_LAT
    ,GEOG_COORD_LONG GEOG_COORD_LONG
    ,REBATE_REBATE_PROGRAM_CODE REBATE_REBATE_PROGRAM_CODE
    ,NULL TOLL_INEQUITY_PROGRAM_FLAG
    ,I_TOLL_PARTICIPATION I_TOLL_PARTICIPATION
    ,IN_LANE_DISC_PERCENT IN_LANE_DISC_PERCENT
    ,S_BOUND_TIME S_BOUND_TIME
    ,N_BOUND_TIME N_BOUND_TIME
    ,THRESHOLD THRESHOLD
    ,CLASS2_RATE_FLAG CLASS2_RATE_FLAG
    ,AVC_THRESHOLD AVC_THRESHOLD
    ,NULL  VR_TOLL_PARTICIPATION
    ,UTURN_INTERVAL UTURN_INTERVAL
    ,FTE_PLAZA FTE_PLAZA
    ,MIN_FARE_PLAZA_ID MIN_FARE_PLAZA_ID
    ,IAG_PLAZA_ID IAG_PLAZA_ID
    ,NULL CROSS_READ_PLAZA_ID
    ,VBTOL_EFFECTIVE_DATE VBTOL_EFFECTIVE_DATE
    ,TRIP_PLAZA TRIP_PLAZA
    ,'SUNPASS' SOURCE_SYSTEM
FROM PA_PLAZA;

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PA_PLAZA_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN */

    /*ETL SECTION END   */

    /*Bulk insert */ 
    FORALL i in DM_PA_PLAZA_tab.first .. DM_PA_PLAZA_tab.last
           INSERT INTO DM_PA_PLAZA VALUES DM_PA_PLAZA_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


