/********************************************************
*
* Name: DM_PAYMT_ITM_HST_INFO_PROC
* Created by: RH, 5/31/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_PAYMT_ITM_HST_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_PAYMT_ITM_HST_INFO_PROC IS

P_BEGIN_DATE  DATE;
P_END_DATE    DATE;


TYPE DM_PAYMT_ITM_HST_INFO_TYP IS TABLE OF DM_PAYMT_ITM_HST_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PAYMT_ITM_HST_INFO_tab DM_PAYMT_ITM_HST_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    pd.PRODUCT_PUR_PRODUCT_CODE CATEGORY
    ,pd.PRODUCT_PUR_PRODUCT_CODE SUB_CATEGORY
    ,pd.PRODUCT_PUR_PRODUCT_CODE TRANS_TYPE
--    ,(select PROD_ABBRV from PA_PUR_PRODUCT where PUR_PRODUCT_CODE = pd.PRODUCT_PUR_PRODUCT_CODE) TRANS_TYPE    
    ,nvl(pd.PROD_AMT,0) AMOUNT
    ,'FTE' ENDO_AGENCY
    ,'FTE' REVENUE_AGENCY
    ,(select pur.PUR_PRODUCT_DESC from PA_PUR_PRODUCT pur
        where pur.PUR_PRODUCT_CODE = pd.PRODUCT_PUR_PRODUCT_CODE) DESCRIPTION   
    ,NULL TRANSFER_REASON
    ,NULL NOTICE_NUMBER
    ,NULL SEQUENCE_NUMBER
    ,p.PUR_ID PARENT_PAYMENT_ID   -- PA_PURCHASE
    ,p.PUR_TRANS_DATE CREATED   -- PA_PURCHASE
--    ,pp.EMP_EMP_CODE CREATED_BY  -- OR below
    ,(select pp.EMP_EMP_CODE from PA_PURCHASE_PAYMENT pp
        where pp.PUR_PUR_ID = p.PUR_ID) CREATED_BY   
    ,NULL LAST_UPD
    ,NULL LAST_UPD_BY
    ,p.PUR_ID INVOICE_NUM   -- PA_PURCHASE
    ,NULL INVOICE_REF_ID
    ,'SUNTOLL' SOURCE_SYSTEM
FROM PA_PURCHASE p
    ,PA_PURCHASE_DETAIL pd
--    ,PA_PURCHASE_PAYMENT pp
WHERE p.PUR_ID = pd.PUR_PUR_ID (+)
--AND   p.PUR_ID = pp.PUR_PUR_ID (+)
; -- FTE source

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PAYMT_ITM_HST_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_PAYMT_ITM_HST_INFO_tab.first .. DM_PAYMT_ITM_HST_INFO_tab.last
           INSERT INTO DM_PAYMT_ITM_HST_INFO VALUES DM_PAYMT_ITM_HST_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


