/********************************************************
*
* Name: DM_PAYMT_ITM_INFO_PROC
* Created by: RH, 4/16/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_PAYMT_ITM_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_PAYMT_ITM_INFO_PROC IS

TYPE DM_PAYMT_ITM_INFO_TYP IS TABLE OF DM_PAYMT_ITM_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PAYMT_ITM_INFO_tab DM_PAYMT_ITM_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    PRODUCT_PUR_PRODUCT_CODE CATEGORY
    ,PRODUCT_PUR_PRODUCT_CODE SUB_CATEGORY
    ,PRODUCT_PUR_PRODUCT_CODE TRANS_TYPE
    ,PROD_AMT AMOUNT
    ,NULL ENDO_AGENCY
    ,NULL REVENUE_AGENCY
    ,PUR_PRODUCT_DESC DESCRIPTION   -- PA_PUR_PRODUCT
    ,NULL TRANSFER_REASON
    ,NULL NOTICE_NUMBER
    ,NULL SEQUENCE_NUMBER
    ,PUR_ID PARENT_PAYMENT_ID   -- PA_PURCHASE
    ,PUR_TRANS_DATE CREATED   -- PA_PURCHASE
    ,EMP_EMP_CODE CREATED_BY
    ,NULL LAST_UPD
    ,NULL LAST_UPD_BY
    ,PUR_ID INVOICE_NUM   -- PA_PURCHASE
    ,NULL INVOICE_REF_ID
    ,'SUNTOLL' SOURCE_SYSTEM
FROM PA_PURCHASE_DETAIL; -- source

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PAYMT_ITM_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_PAYMT_ITM_INFO_tab.first .. DM_PAYMT_ITM_INFO_tab.last
           INSERT INTO DM_PAYMT_ITM_INFO VALUES DM_PAYMT_ITM_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


