/********************************************************
*
* Name: DM_PAYMT_INFO_PROC
* Created by: RH, 4/17/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_PAYMT_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_PAYMT_INFO_PROC IS

TYPE DM_PAYMT_INFO_TYP IS TABLE OF DM_PAYMT_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PAYMT_INFO_tab DM_PAYMT_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    ACCT_NUM ACCOUNT_NUMBER
    ,PUR_TRANS_DATE TX_DT  -- PA_PURCHASE
    ,PAYTYPE_PAYMENT_TYPE_CODE PAY_TYPE
    ,PRODUCT_PUR_PRODUCT_CODE TRAN_TYPE
    ,PUR_PAY_AMT AMOUNT
    ,PRODUCT_PUR_PRODUCT_CODE REVERSED  -- PA_PURCHASE_DETAIL.PRODUCT_PUR_PRODUCT_CODE 
    ,to_char(PUR_CREDIT_EXP_DATE,'MM') EXP_MONTH
    ,PUR_CREDIT_EXP_DATE EXP_YEAR
    ,PUR_CREDIT_ACCT_NUM CREDIT_CARD_NUMBER
    ,CHK_ACCT_NUM BANK_ACCOUNT_NUMBER
    ,ABA_NUMBER BANK_ROUTING_NUMBER
    ,CHECH_NUM CHECK_NUMBER
    ,NULL NSF_FEE -- DERIVED  PA_PURCHASE_DETAIL.RODUCT_PUR_PRODUCT_CODE
    ,PUR_PUR_ID PAYMENT_REFERENCE_NUM
    ,EMP_EMP_CODE EMPLOYEE_NUMBER
    ,PUR_PAY_ID TRANSACTION_ID
    ,NULL ORG_TRANSACTION_ID  -- Derived from product code and VES_REF_NUM from PA_PURCHASE_DETAIL table.
    ,NULL XREF_TRANSACTION_ID  -- No mapping
    ,PUR_CREDIT_AUTH_NUM CC_RESPONSE_CODE
    ,CC_GATEWAY_REF_ID EXTERNAL_REFERENCE_NUM
    ,NULL MISS_APPLIED
    ,NULL DESCRIPTION  -- No mapping
    ,REF_APPROVED_DATE REFUND_STATUS  -- PA_REFUND_REQUEST
    ,NULL REFUND_CHECK_NUM
    ,NULL TOD_ID
    ,PUR_TRANS_DATE CREATED -- PA_PURCHASE
    ,EMP_EMP_CODE CREATED_BY
    ,NULL LAST_UPD
    ,NULL LAST_UPD_BY
    ,'SUNTOLL' SOURCE_SYSTEM
    ,CC_GATEWAY_REQ_ID CC_GATEWAY_REQ_ID
    ,CC_TXN_REF_NUM CC_TXN_REF_NUM
FROM PA_PURCHASE_PAYMENT; -- source

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PAYMT_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_PAYMT_INFO_tab.first .. DM_PAYMT_INFO_tab.last
           INSERT INTO DM_PAYMT_INFO VALUES DM_PAYMT_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


