/********************************************************
*
* Name: DM_PAYMT_HST_INFO_PROC
* Created by: RH, 5/31/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_PAYMT_HST_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

--CREATE OR REPLACE PROCEDURE DM_PAYMT_HST_INFO_PROC IS
DECLARE

TYPE DM_PAYMT_HST_INFO_TYP IS TABLE OF DM_PAYMT_HST_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PAYMT_HST_INFO_tab DM_PAYMT_HST_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    pp.ACCT_ACCT_NUM ACCOUNT_NUMBER
    ,p.PUR_TRANS_DATE TX_DT  -- PA_PURCHASE
    ,pp.PAYTYPE_PAYMENT_TYPE_CODE PAY_TYPE
    ,pd.PRODUCT_PUR_PRODUCT_CODE TRAN_TYPE
--    ,(select PROD_ABBRV from PA_PUR_PRODUCT where PUR_PRODUCT_CODE = pd.PRODUCT_PUR_PRODUCT_CODE) TRAN_TYPE    ?
    ,pp.PUR_PAY_AMT AMOUNT
    ,pd.PRODUCT_PUR_PRODUCT_CODE REVERSED  -- PA_PURCHASE_DETAIL.PRODUCT_PUR_PRODUCT_CODE 
--    ,(select PROD_ABBRV from PA_PUR_PRODUCT where PUR_PRODUCT_CODE = pd.PRODUCT_PUR_PRODUCT_CODE) REVERSED    ?
    ,to_char(to_date(pp.PUR_CREDIT_EXP_DATE,'MM/YY'),'MM') EXP_MONTH
    ,to_char(to_date(pp.PUR_CREDIT_EXP_DATE,'MM/YY'),'YYYY') EXP_YEAR
    ,pp.PUR_CREDIT_ACCT_NUM CREDIT_CARD_NUMBER
    ,pp.CHK_ACCT_NUM BANK_ACCOUNT_NUMBER
    ,pp.ABA_NUMBER BANK_ROUTING_NUMBER
    ,pp.CHECK_NUM CHECK_NUMBER
    ,NULL NSF_FEE -- DERIVED  PA_PURCHASE_DETAIL.RODUCT_PUR_PRODUCT_CODE ?
    ,pp.PUR_PUR_ID PAYMENT_REFERENCE_NUM
    ,pp.EMP_EMP_CODE EMPLOYEE_NUMBER
    ,pp.PUR_PAY_ID TRANSACTION_ID
    ,NULL ORG_TRANSACTION_ID  -- Derived from product code and VES_REF_NUM from PA_PURCHASE_DETAIL table.
    ,pd.VES_REF_NUM ORG_TRANSACTION_ID  -- Derived from product code and VES_REF_NUM from PA_PURCHASE_DETAIL table.
--    ,(select PROD_ABBRV from PA_PUR_PRODUCT where PUR_PRODUCT_CODE = pd.PRODUCT_PUR_PRODUCT_CODE) REVERSED    
    ,NULL XREF_TRANSACTION_ID  -- No mapping
    ,pp.PUR_CREDIT_AUTH_NUM CC_RESPONSE_CODE
    ,pp.CC_GATEWAY_REF_ID EXTERNAL_REFERENCE_NUM
    ,NULL MISS_APPLIED
    ,NULL DESCRIPTION  -- No mapping
-- If REF_APPROVED_DATE is populated, then the refund status will be populated. REF_DECLINE_REASON_ID will get the status of the refund.
-- 1=UNAPPROVED, 2=APPROVED, 3=PARTIAL, 4=REJECTED.
    ,CASE WHEN rr.REF_APPROVED_DATE IS NOT NULL THEN 
        decode(rr.REFUND_STATUS_ID, 1,'UNAPPROVED', 2,'APPROVED', 3,'PARTIAL', 4,'REJECTED',NULL) 
      END REFUND_STATUS 
    ,NULL REFUND_CHECK_NUM
    ,NULL TOD_ID
    ,p.PUR_TRANS_DATE CREATED -- PA_PURCHASE
    ,pp.EMP_EMP_CODE CREATED_BY
    ,NULL LAST_UPD
    ,NULL LAST_UPD_BY
    ,'SUNTOLL' SOURCE_SYSTEM
    ,pp.CC_GATEWAY_REQ_ID CC_GATEWAY_REQ_ID
    ,pp.CC_TXN_REF_NUM CC_TXN_REF_NUM
FROM PA_PURCHASE p
    ,PA_PURCHASE_PAYMENT pp
    ,PA_PURCHASE_DETAIL pd
    ,PA_REFUND_REQUEST rr
WHERE p.PUR_ID = pd.PUR_PUR_ID (+)
AND   p.PUR_ID = pp.PUR_PUR_ID (+)
AND   p.PUR_ID = rr.PUR_PUR_ID (+)
and rownum<111
; -- source

BEGIN

  DBMS_OUTPUT.PUT_LINE('Start DM_PAYMT_HST_INFO load at: '||to_char(SYSDATE,'MMM-DD-YYYY HH:MM:SS'));
  
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PAYMT_HST_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_PAYMT_HST_INFO_tab.first .. DM_PAYMT_HST_INFO_tab.last
           INSERT INTO DM_PAYMT_HST_INFO VALUES DM_PAYMT_HST_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


