/********************************************************
*
* Name: DM_ACCOUNT_INFO_PROC
* Created by: DT, 4/11/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_ACCOUNT_INFO
*
********************************************************/

CREATE OR REPLACE PROCEDURE DM_ACCOUNT_INFO_PROC IS
l_ACCOUNT_CLOSE_DATE dbms_sql.DATE_table;
l_ACCOUNT_CLOSE_PEND_DT dbms_sql.DATE_table;
l_ACCOUNT_LOCKED dbms_sql.CHAR_table;
l_ACCOUNT_NAME dbms_sql.VARCHAR2_table;
l_ACCOUNT_NUMBER dbms_sql.VARCHAR2_table;
l_ACCOUNT_OPEN_DATE dbms_sql.DATE_table;
l_ACCOUNT_STATUS dbms_sql.VARCHAR2_table;
l_ACCOUNT_STATUS_DATETIME dbms_sql.DATE_table;
l_ACCOUNT_TYPE dbms_sql.VARCHAR2_table;
l_ACC_LOCKED_DATETIME dbms_sql.DATE_table;
l_ANONYMOUS_ACCOUNT dbms_sql.CHAR_table;
l_APPLICATION_NUMBER dbms_sql.VARCHAR2_table;
l_BANKRUPTCY_DATE dbms_sql.DATE_table;
l_BKTY_CASEID dbms_sql.VARCHAR2_table;
l_BKTY_DICHG_DATE dbms_sql.DATE_table;
l_BKTY_DISMISS_DATE dbms_sql.DATE_table;
l_BKTY_FILE_DATE dbms_sql.DATE_table;
l_BKTY_NOTIFY_BY dbms_sql.VARCHAR2_table;
l_CAST_ACCOUNT_FLAG dbms_sql.CHAR_table;
l_CHALLENGE_ANSWER dbms_sql.VARCHAR2_table;
l_CHALLENGE_QUESTION dbms_sql.VARCHAR2_table;
l_CHARGEBACK_RELEASED_DT dbms_sql.DATE_table;
l_COLLECTION_AGENCY dbms_sql.VARCHAR2_table;
l_COMPANY_NAME dbms_sql.VARCHAR2_table;
l_CORRESPONDENCE_DEL_MODE dbms_sql.VARCHAR2_table;
l_COURT_FLAG dbms_sql.CHAR_table;
l_CREATED dbms_sql.DATE_table;
l_CREATED_BY dbms_sql.VARCHAR2_table;
l_DBA dbms_sql.VARCHAR2_table;
l_DECEASED dbms_sql.CHAR_table;
l_DO_NOT_CALL dbms_sql.CHAR_table;
l_EMAIL_ADDRESS dbms_sql.VARCHAR2_table;
l_EXPIRATION_DATE dbms_sql.DATE_table;
l_FEIN_NUMBER dbms_sql.NUMBER_table;
l_IS_POSTPAID dbms_sql.CHAR_table;
l_IS_REGISTERED dbms_sql.VARCHAR2_table;
l_IS_SURVEY_OPTED dbms_sql.CHAR_table;
l_LANGUAGE_PREFERENCE dbms_sql.VARCHAR2_table;
l_LAST_INVOICE_DATE dbms_sql.DATE_table;
l_LAST_UPD dbms_sql.DATE_table;
l_LAST_UPD_BY dbms_sql.VARCHAR2_table;
l_MOBILE_ALERTS dbms_sql.VARCHAR2_table;
l_MOTHERS_MAIDEN_NAME dbms_sql.VARCHAR2_table;
l_NSF_LOCK_RELEASED_DT dbms_sql.DATE_table;
l_OUTBOUND_DAILER dbms_sql.VARCHAR2_table;
l_OWNER_TYPE dbms_sql.VARCHAR2_table;
l_PIN dbms_sql.NUMBER_table;
l_REBILL_AMOUNT dbms_sql.NUMBER_table;
l_REBILL_THRESHOLD dbms_sql.NUMBER_table;
l_SECONDARY_EMAIL_ADDRESS dbms_sql.VARCHAR2_table;
l_SOURCE_SYSTEM dbms_sql.VARCHAR2_table;
l_STATEMENT_DELIVERY_MODE dbms_sql.VARCHAR2_table;
l_STATEMENT_PERIOD dbms_sql.VARCHAR2_table;
l_SUSPENDED_DATE dbms_sql.DATE_table;
l_TAX_EXEMPTION_ID dbms_sql.VARCHAR2_table;
l_VIDEO_ACCT_STATUS dbms_sql.NUMBER_table;

p_count dbms_sql.number_table;
P_ARRAY_SIZE NUMBER:=10000;

CURSOR C1 IS SELECT * FROM FTE_SOURCE_TABLE; /* replace FTE_SOURCE_TABLE to actual table*/

BEGIN

  OPEN C1;

  LOOP

  /*Bulk select */
  FETCH C1 BULK COLLECT INTO
  l_ACCOUNT_CLOSE_DATE
  ,l_ACCOUNT_CLOSE_PEND_DT
  ,l_ACCOUNT_LOCKED
  ,l_ACCOUNT_NAME
  ,l_ACCOUNT_NUMBER
  ,l_ACCOUNT_OPEN_DATE
  ,l_ACCOUNT_STATUS
  ,l_ACCOUNT_STATUS_DATETIME
  ,l_ACCOUNT_TYPE
  ,l_ACC_LOCKED_DATETIME
  ,l_ANONYMOUS_ACCOUNT
  ,l_APPLICATION_NUMBER
  ,l_BANKRUPTCY_DATE
  ,l_BKTY_CASEID
  ,l_BKTY_DICHG_DATE
  ,l_BKTY_DISMISS_DATE
  ,l_BKTY_FILE_DATE
  ,l_BKTY_NOTIFY_BY
  ,l_CAST_ACCOUNT_FLAG
  ,l_CHALLENGE_ANSWER
  ,l_CHALLENGE_QUESTION
  ,l_CHARGEBACK_RELEASED_DT
  ,l_COLLECTION_AGENCY
  ,l_COMPANY_NAME
  ,l_CORRESPONDENCE_DEL_MODE
  ,l_COURT_FLAG
  ,l_CREATED
  ,l_CREATED_BY
  ,l_DBA
  ,l_DECEASED
  ,l_DO_NOT_CALL
  ,l_EMAIL_ADDRESS
  ,l_EXPIRATION_DATE
  ,l_FEIN_NUMBER
  ,l_IS_POSTPAID
  ,l_IS_REGISTERED
  ,l_IS_SURVEY_OPTED
  ,l_LANGUAGE_PREFERENCE
  ,l_LAST_INVOICE_DATE
  ,l_LAST_UPD
  ,l_LAST_UPD_BY
  ,l_MOBILE_ALERTS
  ,l_MOTHERS_MAIDEN_NAME
  ,l_NSF_LOCK_RELEASED_DT
  ,l_OUTBOUND_DAILER
  ,l_OWNER_TYPE
  ,l_PIN
  ,l_REBILL_AMOUNT
  ,l_REBILL_THRESHOLD
  ,l_SECONDARY_EMAIL_ADDRESS
  ,l_SOURCE_SYSTEM
  ,l_STATEMENT_DELIVERY_MODE
  ,l_STATEMENT_PERIOD
  ,l_SUSPENDED_DATE
  ,l_TAX_EXEMPTION_ID
  ,l_VIDEO_ACCT_STATUS
  LIMIT P_ARRAY_SIZE;

  /*Bulk transform, l_ACCOUNT_CLOSE_DATE.COUNT is the upper limit of the loop */


  /*Bulk insert */                           
  FORALL I IN 1 .. l_ACCOUNT_CLOSE_DATE.COUNT
    INSERT INTO DM_ACCOUNT_INFO
    ( ACCOUNT_CLOSE_DATE
    ,ACCOUNT_CLOSE_PEND_DT
    ,ACCOUNT_LOCKED
    ,ACCOUNT_NAME
    ,ACCOUNT_NUMBER
    ,ACCOUNT_OPEN_DATE
    ,ACCOUNT_STATUS
    ,ACCOUNT_STATUS_DATETIME
    ,ACCOUNT_TYPE
    ,ACC_LOCKED_DATETIME
    ,ANONYMOUS_ACCOUNT
    ,APPLICATION_NUMBER
    ,BANKRUPTCY_DATE
    ,BKTY_CASEID
    ,BKTY_DICHG_DATE
    ,BKTY_DISMISS_DATE
    ,BKTY_FILE_DATE
    ,BKTY_NOTIFY_BY
    ,CAST_ACCOUNT_FLAG
    ,CHALLENGE_ANSWER
    ,CHALLENGE_QUESTION
    ,CHARGEBACK_RELEASED_DT
    ,COLLECTION_AGENCY
    ,COMPANY_NAME
    ,CORRESPONDENCE_DEL_MODE
    ,COURT_FLAG
    ,CREATED
    ,CREATED_BY
    ,DBA
    ,DECEASED
    ,DO_NOT_CALL
    ,EMAIL_ADDRESS
    ,EXPIRATION_DATE
    ,FEIN_NUMBER
    ,IS_POSTPAID
    ,IS_REGISTERED
    ,IS_SURVEY_OPTED
    ,LANGUAGE_PREFERENCE
    ,LAST_INVOICE_DATE
    ,LAST_UPD
    ,LAST_UPD_BY
    ,MOBILE_ALERTS
    ,MOTHERS_MAIDEN_NAME
    ,NSF_LOCK_RELEASED_DT
    ,OUTBOUND_DAILER
    ,OWNER_TYPE
    ,PIN
    ,REBILL_AMOUNT
    ,REBILL_THRESHOLD
    ,SECONDARY_EMAIL_ADDRESS
    ,SOURCE_SYSTEM
    ,STATEMENT_DELIVERY_MODE
    ,STATEMENT_PERIOD
    ,SUSPENDED_DATE
    ,TAX_EXEMPTION_ID
    ,VIDEO_ACCT_STATUS
    )
    values
    ( l_ACCOUNT_CLOSE_DATE(i)
    ,l_ACCOUNT_CLOSE_PEND_DT(i)
    ,l_ACCOUNT_LOCKED(i)
    ,l_ACCOUNT_NAME(i)
    ,l_ACCOUNT_NUMBER(i)
    ,l_ACCOUNT_OPEN_DATE(i)
    ,l_ACCOUNT_STATUS(i)
    ,l_ACCOUNT_STATUS_DATETIME(i)
    ,l_ACCOUNT_TYPE(i)
    ,l_ACC_LOCKED_DATETIME(i)
    ,l_ANONYMOUS_ACCOUNT(i)
    ,l_APPLICATION_NUMBER(i)
    ,l_BANKRUPTCY_DATE(i)
    ,l_BKTY_CASEID(i)
    ,l_BKTY_DICHG_DATE(i)
    ,l_BKTY_DISMISS_DATE(i)
    ,l_BKTY_FILE_DATE(i)
    ,l_BKTY_NOTIFY_BY(i)
    ,l_CAST_ACCOUNT_FLAG(i)
    ,l_CHALLENGE_ANSWER(i)
    ,l_CHALLENGE_QUESTION(i)
    ,l_CHARGEBACK_RELEASED_DT(i)
    ,l_COLLECTION_AGENCY(i)
    ,l_COMPANY_NAME(i)
    ,l_CORRESPONDENCE_DEL_MODE(i)
    ,l_COURT_FLAG(i)
    ,l_CREATED(i)
    ,l_CREATED_BY(i)
    ,l_DBA(i)
    ,l_DECEASED(i)
    ,l_DO_NOT_CALL(i)
    ,l_EMAIL_ADDRESS(i)
    ,l_EXPIRATION_DATE(i)
    ,l_FEIN_NUMBER(i)
    ,l_IS_POSTPAID(i)
    ,l_IS_REGISTERED(i)
    ,l_IS_SURVEY_OPTED(i)
    ,l_LANGUAGE_PREFERENCE(i)
    ,l_LAST_INVOICE_DATE(i)
    ,l_LAST_UPD(i)
    ,l_LAST_UPD_BY(i)
    ,l_MOBILE_ALERTS(i)
    ,l_MOTHERS_MAIDEN_NAME(i)
    ,l_NSF_LOCK_RELEASED_DT(i)
    ,l_OUTBOUND_DAILER(i)
    ,l_OWNER_TYPE(i)
    ,l_PIN(i)
    ,l_REBILL_AMOUNT(i)
    ,l_REBILL_THRESHOLD(i)
    ,l_SECONDARY_EMAIL_ADDRESS(i)
    ,l_SOURCE_SYSTEM(i)
    ,l_STATEMENT_DELIVERY_MODE(i)
    ,l_STATEMENT_PERIOD(i)
    ,l_SUSPENDED_DATE(i)
    ,l_TAX_EXEMPTION_ID(i)
    ,l_VIDEO_ACCT_STATUS(i)
    ) 
      ;
    EXIT WHEN C1%NOTFOUND;

    /*Summary, load status, process status update */

    COMMIT;

  END LOOP;


  CLOSE C1;

  /*Summary, load status, process status update */

  COMMIT;

END;
/
SHOW ERRORS

