/********************************************************
*
* Name: DM_ACCOUNT_INFO_PROC
* Created by: DT, 4/11/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_ACCOUNT_INFO
*
********************************************************/

CREATE OR REPLACE PROCEDURE DM_ACCOUNT_INFO_PROC IS
l_ACCOUNT_CLOSE_DATE DATE dbms_sql._table;
l_ACCOUNT_CLOSE_PEND_DT DATE dbms_sql._table;
l_ACCOUNT_LOCKED CHAR dbms_sql._table;
l_ACCOUNT_NAME VARCHAR2 dbms_sql._table;
l_ACCOUNT_NUMBER VARCHAR2 dbms_sql._table;
l_ACCOUNT_OPEN_DATE DATE dbms_sql._table;
l_ACCOUNT_STATUS VARCHAR2 dbms_sql._table;
l_ACCOUNT_STATUS_DATETIME DATE dbms_sql._table;
l_ACCOUNT_TYPE VARCHAR2 dbms_sql._table;
l_ACC_LOCKED_DATETIME DATE dbms_sql._table;
l_ANONYMOUS_ACCOUNT CHAR dbms_sql._table;
l_APPLICATION_NUMBER VARCHAR2 dbms_sql._table;
l_BANKRUPTCY_DATE DATE dbms_sql._table;
l_BKTY_CASEID VARCHAR2 dbms_sql._table;
l_BKTY_DICHG_DATE DATE dbms_sql._table;
l_BKTY_DISMISS_DATE DATE dbms_sql._table;
l_BKTY_FILE_DATE DATE dbms_sql._table;
l_BKTY_NOTIFY_BY VARCHAR2 dbms_sql._table;
l_CAST_ACCOUNT_FLAG CHAR dbms_sql._table;
l_CHALLENGE_ANSWER VARCHAR2 dbms_sql._table;
l_CHALLENGE_QUESTION VARCHAR2 dbms_sql._table;
l_CHARGEBACK_RELEASED_DT DATE dbms_sql._table;
l_COLLECTION_AGENCY VARCHAR2 dbms_sql._table;
l_COMPANY_NAME VARCHAR2 dbms_sql._table;
l_CORRESPONDENCE_DEL_MODE VARCHAR2 dbms_sql._table;
l_COURT_FLAG CHAR dbms_sql._table;
l_CREATED DATE dbms_sql._table;
l_CREATED_BY VARCHAR2 dbms_sql._table;
l_DBA VARCHAR2 dbms_sql._table;
l_DECEASED CHAR dbms_sql._table;
l_DO_NOT_CALL CHAR dbms_sql._table;
l_EMAIL_ADDRESS VARCHAR2 dbms_sql._table;
l_EXPIRATION_DATE DATE dbms_sql._table;
l_FEIN_NUMBER NUMBER dbms_sql._table;
l_IS_POSTPAID CHAR dbms_sql._table;
l_IS_REGISTERED VARCHAR2 dbms_sql._table;
l_IS_SURVEY_OPTED CHAR dbms_sql._table;
l_LANGUAGE_PREFERENCE VARCHAR2 dbms_sql._table;
l_LAST_INVOICE_DATE DATE dbms_sql._table;
l_LAST_UPD DATE dbms_sql._table;
l_LAST_UPD_BY VARCHAR2 dbms_sql._table;
l_MOBILE_ALERTS VARCHAR2 dbms_sql._table;
l_MOTHERS_MAIDEN_NAME VARCHAR2 dbms_sql._table;
l_NSF_LOCK_RELEASED_DT DATE dbms_sql._table;
l_OUTBOUND_DAILER VARCHAR2 dbms_sql._table;
l_OWNER_TYPE VARCHAR2 dbms_sql._table;
l_PIN NUMBER dbms_sql._table;
l_REBILL_AMOUNT NUMBER dbms_sql._table;
l_REBILL_THRESHOLD NUMBER dbms_sql._table;
l_SECONDARY_EMAIL_ADDRESS VARCHAR2 dbms_sql._table;
l_SOURCE_SYSTEM VARCHAR2 dbms_sql._table;
l_STATEMENT_DELIVERY_MODE VARCHAR2 dbms_sql._table;
l_STATEMENT_PERIOD VARCHAR2 dbms_sql._table;
l_SUSPENDED_DATE DATE dbms_sql._table;
l_TAX_EXEMPTION_ID VARCHAR2 dbms_sql._table;
l_VIDEO_ACCT_STATUS NUMBER dbms_sql._table;

p_count dbms_sql.number_table;
P_ARRAY_SIZE NUMBER:=10000;

CURSOR C1 IS SELECT * FROM FTE_SOURCE_TABLE; /* replace FTE_SOURCE_TABLE to actual table*/

BEGIN

  OPEN C1;

  LOOP

  /*Bulk select */
  FETCH C1 BULK COLLECT INTO
  l_ACCOUNT_CLOSE_DATEDATE
  ,l_ACCOUNT_CLOSE_PEND_DT DATE
  ,l_ACCOUNT_LOCKED CHAR
  ,l_ACCOUNT_NAME VARCHAR2
  ,l_ACCOUNT_NUMBER VARCHAR2
  ,l_ACCOUNT_OPEN_DATE DATE
  ,l_ACCOUNT_STATUS VARCHAR2
  ,l_ACCOUNT_STATUS_DATETIME DATE
  ,l_ACCOUNT_TYPE VARCHAR2
  ,l_ACC_LOCKED_DATETIME DATE
  ,l_ANONYMOUS_ACCOUNT CHAR
  ,l_APPLICATION_NUMBER VARCHAR2
  ,l_BANKRUPTCY_DATE DATE
  ,l_BKTY_CASEID VARCHAR2
  ,l_BKTY_DICHG_DATE DATE
  ,l_BKTY_DISMISS_DATE DATE
  ,l_BKTY_FILE_DATE DATE
  ,l_BKTY_NOTIFY_BY VARCHAR2
  ,l_CAST_ACCOUNT_FLAG CHAR
  ,l_CHALLENGE_ANSWER VARCHAR2
  ,l_CHALLENGE_QUESTION VARCHAR2
  ,l_CHARGEBACK_RELEASED_DT DATE
  ,l_COLLECTION_AGENCY VARCHAR2
  ,l_COMPANY_NAME VARCHAR2
  ,l_CORRESPONDENCE_DEL_MODE VARCHAR2
  ,l_COURT_FLAG CHAR
  ,l_CREATED DATE
  ,l_CREATED_BY VARCHAR2
  ,l_DBA VARCHAR2
  ,l_DECEASED CHAR
  ,l_DO_NOT_CALL CHAR
  ,l_EMAIL_ADDRESS VARCHAR2
  ,l_EXPIRATION_DATE DATE
  ,l_FEIN_NUMBER NUMBER
  ,l_IS_POSTPAID CHAR
  ,l_IS_REGISTERED VARCHAR2
  ,l_IS_SURVEY_OPTED CHAR
  ,l_LANGUAGE_PREFERENCE VARCHAR2
  ,l_LAST_INVOICE_DATE DATE
  ,l_LAST_UPD DATE
  ,l_LAST_UPD_BY VARCHAR2
  ,l_MOBILE_ALERTS VARCHAR2
  ,l_MOTHERS_MAIDEN_NAME VARCHAR2
  ,l_NSF_LOCK_RELEASED_DT DATE
  ,l_OUTBOUND_DAILER VARCHAR2
  ,l_OWNER_TYPE VARCHAR2
  ,l_PIN NUMBER
  ,l_REBILL_AMOUNT NUMBER
  ,l_REBILL_THRESHOLD NUMBER
  ,l_SECONDARY_EMAIL_ADDRESS VARCHAR2
  ,l_SOURCE_SYSTEM VARCHAR2
  ,l_STATEMENT_DELIVERY_MODE VARCHAR2
  ,l_STATEMENT_PERIOD VARCHAR2
  ,l_SUSPENDED_DATE DATE
  ,l_TAX_EXEMPTION_ID VARCHAR2
  ,l_VIDEO_ACCT_STATUS NUMBER
  LIMIT P_ARRAY_SIZE;

  /*Bulk transform, l_ACCOUNT_CLOSE_DATE DATE.COUNT is the upper limit of the loop */

  /*Bulk insert */                           
  FORALL I IN 1 .. l_ACCOUNT_CLOSE_DATE DATE.COUNT
    INSERT INTO DM_ACCOUNT_INFO
    ( ACCOUNT_CLOSE_DATE DATE
    ,ACCOUNT_CLOSE_PEND_DT DATE
    ,ACCOUNT_LOCKED CHAR
    ,ACCOUNT_NAME VARCHAR2
    ,ACCOUNT_NUMBER VARCHAR2
    ,ACCOUNT_OPEN_DATE DATE
    ,ACCOUNT_STATUS VARCHAR2
    ,ACCOUNT_STATUS_DATETIME DATE
    ,ACCOUNT_TYPE VARCHAR2
    ,ACC_LOCKED_DATETIME DATE
    ,ANONYMOUS_ACCOUNT CHAR
    ,APPLICATION_NUMBER VARCHAR2
    ,BANKRUPTCY_DATE DATE
    ,BKTY_CASEID VARCHAR2
    ,BKTY_DICHG_DATE DATE
    ,BKTY_DISMISS_DATE DATE
    ,BKTY_FILE_DATE DATE
    ,BKTY_NOTIFY_BY VARCHAR2
    ,CAST_ACCOUNT_FLAG CHAR
    ,CHALLENGE_ANSWER VARCHAR2
    ,CHALLENGE_QUESTION VARCHAR2
    ,CHARGEBACK_RELEASED_DT DATE
    ,COLLECTION_AGENCY VARCHAR2
    ,COMPANY_NAME VARCHAR2
    ,CORRESPONDENCE_DEL_MODE VARCHAR2
    ,COURT_FLAG CHAR
    ,CREATED DATE
    ,CREATED_BY VARCHAR2
    ,DBA VARCHAR2
    ,DECEASED CHAR
    ,DO_NOT_CALL CHAR
    ,EMAIL_ADDRESS VARCHAR2
    ,EXPIRATION_DATE DATE
    ,FEIN_NUMBER NUMBER
    ,IS_POSTPAID CHAR
    ,IS_REGISTERED VARCHAR2
    ,IS_SURVEY_OPTED CHAR
    ,LANGUAGE_PREFERENCE VARCHAR2
    ,LAST_INVOICE_DATE DATE
    ,LAST_UPD DATE
    ,LAST_UPD_BY VARCHAR2
    ,MOBILE_ALERTS VARCHAR2
    ,MOTHERS_MAIDEN_NAME VARCHAR2
    ,NSF_LOCK_RELEASED_DT DATE
    ,OUTBOUND_DAILER VARCHAR2
    ,OWNER_TYPE VARCHAR2
    ,PIN NUMBER
    ,REBILL_AMOUNT NUMBER
    ,REBILL_THRESHOLD NUMBER
    ,SECONDARY_EMAIL_ADDRESS VARCHAR2
    ,SOURCE_SYSTEM VARCHAR2
    ,STATEMENT_DELIVERY_MODE VARCHAR2
    ,STATEMENT_PERIOD VARCHAR2
    ,SUSPENDED_DATE DATE
    ,TAX_EXEMPTION_ID VARCHAR2
    ,VIDEO_ACCT_STATUS NUMBER
    )
    values
    ( l_ACCOUNT_CLOSE_DATE DATE(i)
    ,l_ACCOUNT_CLOSE_PEND_DT DATE(i)
    ,l_ACCOUNT_LOCKED CHAR(i)
    ,l_ACCOUNT_NAME VARCHAR2(i)
    ,l_ACCOUNT_NUMBER VARCHAR2(i)
    ,l_ACCOUNT_OPEN_DATE DATE(i)
    ,l_ACCOUNT_STATUS VARCHAR2(i)
    ,l_ACCOUNT_STATUS_DATETIME DATE(i)
    ,l_ACCOUNT_TYPE VARCHAR2(i)
    ,l_ACC_LOCKED_DATETIME DATE(i)
    ,l_ANONYMOUS_ACCOUNT CHAR(i)
    ,l_APPLICATION_NUMBER VARCHAR2(i)
    ,l_BANKRUPTCY_DATE DATE(i)
    ,l_BKTY_CASEID VARCHAR2(i)
    ,l_BKTY_DICHG_DATE DATE(i)
    ,l_BKTY_DISMISS_DATE DATE(i)
    ,l_BKTY_FILE_DATE DATE(i)
    ,l_BKTY_NOTIFY_BY VARCHAR2(i)
    ,l_CAST_ACCOUNT_FLAG CHAR(i)
    ,l_CHALLENGE_ANSWER VARCHAR2(i)
    ,l_CHALLENGE_QUESTION VARCHAR2(i)
    ,l_CHARGEBACK_RELEASED_DT DATE(i)
    ,l_COLLECTION_AGENCY VARCHAR2(i)
    ,l_COMPANY_NAME VARCHAR2(i)
    ,l_CORRESPONDENCE_DEL_MODE VARCHAR2(i)
    ,l_COURT_FLAG CHAR(i)
    ,l_CREATED DATE(i)
    ,l_CREATED_BY VARCHAR2(i)
    ,l_DBA VARCHAR2(i)
    ,l_DECEASED CHAR(i)
    ,l_DO_NOT_CALL CHAR(i)
    ,l_EMAIL_ADDRESS VARCHAR2(i)
    ,l_EXPIRATION_DATE DATE(i)
    ,l_FEIN_NUMBER NUMBER(i)
    ,l_IS_POSTPAID CHAR(i)
    ,l_IS_REGISTERED VARCHAR2(i)
    ,l_IS_SURVEY_OPTED CHAR(i)
    ,l_LANGUAGE_PREFERENCE VARCHAR2(i)
    ,l_LAST_INVOICE_DATE DATE(i)
    ,l_LAST_UPD DATE(i)
    ,l_LAST_UPD_BY VARCHAR2(i)
    ,l_MOBILE_ALERTS VARCHAR2(i)
    ,l_MOTHERS_MAIDEN_NAME VARCHAR2(i)
    ,l_NSF_LOCK_RELEASED_DT DATE(i)
    ,l_OUTBOUND_DAILER VARCHAR2(i)
    ,l_OWNER_TYPE VARCHAR2(i)
    ,l_PIN NUMBER(i)
    ,l_REBILL_AMOUNT NUMBER(i)
    ,l_REBILL_THRESHOLD NUMBER(i)
    ,l_SECONDARY_EMAIL_ADDRESS VARCHAR2(i)
    ,l_SOURCE_SYSTEM VARCHAR2(i)
    ,l_STATEMENT_DELIVERY_MODE VARCHAR2(i)
    ,l_STATEMENT_PERIOD VARCHAR2(i)
    ,l_SUSPENDED_DATE DATE(i)
    ,l_TAX_EXEMPTION_ID VARCHAR2(i)
    ,l_VIDEO_ACCT_STATUS NUMBER(i)
    ) 
      ;
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;
END;
/
SHOW ERRORS

