CREATE INDEX ACCT_ACCT_NUM_IDX ON PATRON.PA_ACCT_FLAGS
(ACCT_ACCT_NUM) tablespace ccss_acct_ind_ts;
 
CREATE INDEX ACCT_NUM_IDX ON PATRON.PA_ACCT_STATUS_HISTORY
(ACCT_NUM) tablespace ccss_acct_ind_ts;
 
CREATE INDEX ACCT_ACCT_NUM_IDX ON PATRON.PA_ACCT_TAX_EXEMPTIONS
(ACCT_ACCT_NUM) tablespace ccss_acct_ind_ts;
 
CREATE INDEX ACCT_NUM_IDX ON PATRON.PA_REBATE_AUTHORITY
(ACCT_NUM) tablespace ccss_acct_ind_ts;
 
CREATE INDEX ACCT_NUM_IDX ON PATRON.PA_TRANSP_LASTTXN_INFO
(ACCT_NUM) tablespace ccss_acct_ind_ts;
 
CREATE INDEX ACCT_NUM_IDX ON PATRON.PA_WEB_LOGIN_INFO
(ACCT_NUM) tablespace ccss_acct_ind_ts;