/********************************************************
*
* Name: DM_AGENCY_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_AGENCY_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_AGENCY_INFO_PROC IS

TYPE DM_AGENCY_INFO_TYP IS TABLE OF DM_AGENCY_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_AGENCY_INFO_tab DM_AGENCY_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL AGENCY_ID
    ,NULL AGENCY_NAME
    ,NULL AGENCY_SHORT_NAME
    ,NULL CONSORTIUM
    ,NULL CURRENT_IAG_VERSION
    ,NULL DEVICE_PREFIX
    ,NULL FILE_PREFIX
    ,NULL IS_HOME_AGENCY
    ,NULL PARENT_AGENCY_ID
    ,NULL STMT_DEFAULT_DURATION
    ,NULL STMT_DELIVERY
    ,NULL STMT_DESCRIPTION
    ,NULL STMT_FREQUENCY
    ,NULL AGENCY_CODE
    ,NULL SOURCE_SYSTEM
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_AGENCY_INFO_tab
    LIMIT P_ARRAY_SIZE;
    EXIT WHEN C1%NOTFOUND;

    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_AGENCY_INFO_tab.first .. DM_AGENCY_INFO_tab.last
           INSERT INTO DM_AGENCY_INFO VALUES DM_AGENCY_INFO_tab(i);
                       

  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


