/********************************************************
*
* Name: DM_DEVICE_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_DEVICE_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_DEVICE_INFO_PROC IS

TYPE DM_DEVICE_INFO_TYP IS TABLE OF DM_DEVICE_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_DEVICE_INFO_tab DM_DEVICE_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL ACCOUNT_NUMBER
    ,NULL DEVICE_NUMBER
    ,NULL DEVICE_MODEL
    ,NULL BOX_NUMBER
    ,NULL AGENCY
    ,NULL EXPIRY_DATE
    ,NULL DOB
    ,NULL VEHICLE_CLASS
    ,NULL CLASS_MISMATCH_FLAG
    ,NULL STATUS_DATE
    ,NULL DEVICE_STATUS
    ,NULL SWAP_PREV_NUMBER
    ,NULL SWAP_NEXT_NUMBER
    ,NULL SWAP_DATE
    ,NULL ISSUE_TYPE
    ,NULL DEVICE_PRICE
    ,NULL DEVICE_DEPOSIT
    ,NULL ASSIGNED_DATE
    ,NULL STORE
    ,NULL RETAILER_ACCOUNT_NUMBER
    ,NULL VALIDATION_CODE
    ,NULL PO_NUMBER
    ,NULL LP_CHECK_REQUIRED
    ,NULL PLATE_NUMBER
    ,NULL PLATE_ASSOCIATED_DT
    ,NULL UNREG_ACCOUNT_NUMBER
    ,NULL CREATED
    ,NULL CREATED_BY
    ,NULL LAST_UPD
    ,NULL LAST_UPD_BY
    ,NULL TRAY_NUMBER
    ,NULL CASE_NUMBER
    ,NULL MANUF_WARRANTY_DT
    ,NULL CUST_WARRANTY_DT
    ,NULL MANUFACTURER
    ,NULL RETAILER_NAME
    ,NULL DEVICE_INTERNAL_NUMBER
    ,NULL MCOMMERCE_FLAG
    ,NULL FRIENDLY_NAME
    ,NULL IAG_CODE
    ,NULL LOT
    ,NULL TERMINATED_STATUS_FLAG
    ,NULL SOURCE_SYSTEM
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_DEVICE_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_DEVICE_INFO_tab.first .. DM_DEVICE_INFO_tab.last
           INSERT INTO DM_DEVICE_INFO VALUES DM_DEVICE_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


