/********************************************************
*
* Name: DM_PLAN_INFO_PLAN1_PROC
* Created by: DT, 4/19/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_PLAN_INFO_PLAN1
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_PLAN_INFO_PLAN1_PROC IS

TYPE DM_PLAN_INFO_PLAN1_TYP IS TABLE OF DM_PLAN_INFO_PLAN1%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PLAN_INFO_PLAN1_tab DM_PLAN_INFO_PLAN1_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    ACCCT_ACCT_NUM ACCOUNT_NUMBER
    ,'BAYWAY ISLES' PLAN_NAME
    ,INVTRANSP_TRANSP_TRANSP_ID DEVICE_NUMBER
    ,BAYWAY_PASS1_DATE START_DATE
    ,case when BAYWAY_PASS1_DATE>to_date('07/01/2016','MM/DD/YYYY') then to_date('06/30/2017','DD/MM/YYYY') else 
     to_date('06/30/2016','DD/MM/YYYY') END_DATE
    ,BAYWAY_PASS1_PAID PLAN_STATUS
    ,'N' AUTO_RENEW
    ,BAYWAY_PASS1_DATE CREATED
    ,NULL CREATED_BY
    ,BAYWAY_PASS1_DATE LAST_UPD
    ,NULL LAST_UPD_BY
    ,NULL SOURCE_SYSTEM
FROM PATRON.PA_ACCT_TRANSP where BAYWAY_PASS1_PAID='Y' 
or BAYWAY_PASS2_PAID='Y';

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PLAN_INFO_PLAN1_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN */
    
    /*ETL SECTION END   */

    /*Bulk insert */ 
    FORALL i in DM_PLAN_INFO_PLAN1_tab.first .. DM_PLAN_INFO_PLAN1_tab.last
           INSERT INTO DM_PLAN_INFO_PLAN1 VALUES DM_PLAN_INFO_PLAN1_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


