/********************************************************
*
* Name: DM_PLAZA_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_PLAZA_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_PLAZA_INFO_PROC IS

TYPE DM_PLAZA_INFO_TYP IS TABLE OF DM_PLAZA_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PLAZA_INFO_tab DM_PLAZA_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL PLAZA_ID
    ,NULL EXTERN_PLAZA_ID
    ,NULL NAME
    ,NULL ADDRESS_ID
    ,NULL OPENED_DT
    ,NULL DMQ_PLAZA_MASK
    ,NULL UPDATE_TS
    ,NULL AGENCY_ID
    ,NULL DEFAULT_PLAN_ID
    ,NULL REVENUE_TIME
    ,NULL COURT_ID
    ,NULL PLAZA_GROUP
    ,NULL IP_ADDRESS
    ,NULL NODENAME
    ,NULL USERNAME
    ,NULL PASSWORD
    ,NULL TS_DIR
    ,NULL TX_DIR
    ,NULL IMAGE_INCOMING_VOLUME
    ,NULL IMAGE_ARCHIVE_VOLUME
    ,NULL PLAZA_TYPE_IND
    ,NULL END_PLAZA_IND
    ,NULL SECTION_CODE_IND
    ,NULL SECTION_ID
    ,NULL PLAZA_ABBR
    ,NULL PLAZA_SEQ_NUMBER
    ,NULL MILEAGE
    ,NULL PLAZA_MASK
    ,NULL HWY_NO
    ,NULL IS_HOME_PLAZA
    ,NULL PORT_NO
    ,NULL CALCULATE_TOLL_AMOUNT
    ,NULL LPR_ENABLED
    ,NULL GRACE_PERIOD
    ,NULL GRACE_TIME
    ,NULL JURISDICTION
    ,NULL IMAGE_RESOLUTION
    ,NULL FACILITY_ID
    ,NULL JURISDICTION_CODE
    ,NULL POSTING_TYPE
    ,NULL HOST_PLAZA_ID
    ,NULL SOURCE_SYSTEM
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PLAZA_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_PLAZA_INFO_tab.first .. DM_PLAZA_INFO_tab.last
           INSERT INTO DM_PLAZA_INFO VALUES DM_PLAZA_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


