/********************************************************
*
* Name: DM_RETAILER_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_RETAILER_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_RETAILER_INFO_PROC IS

TYPE DM_RETAILER_INFO_TYP IS TABLE OF DM_RETAILER_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_RETAILER_INFO_tab DM_RETAILER_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL ACCOUNT_NUMBER
    ,NULL ACCOUNT_NAME
    ,NULL AGENCY
    ,NULL ACCOUNT_TYPE
    ,NULL ACCOUNT_STATUS
    ,NULL ACCOUNT_OPEN_MODE
    ,NULL RETAILER_ACCOUNT_OPEN_DT
    ,NULL PIN
    ,NULL DBA_NAME
    ,NULL COMM_PER_DEVICE
    ,NULL CLOSURE_REASON
    ,NULL CLOSE_DATE
    ,NULL COMENTS
    ,NULL EMAIL_ADDRESS
    ,NULL STORE_NAME
    ,NULL LOGIN_NAME
    ,NULL COMPANY_URL
    ,NULL CHALLENGE_QUESTION
    ,NULL CHALLENGE_ANSWER
    ,NULL CREATED
    ,NULL CREATED_BY
    ,NULL LAST_UPD
    ,NULL LAST_UPD_BY
    ,NULL SOURCE_SYSTEM
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_RETAILER_INFO_tab
    LIMIT P_ARRAY_SIZE;
    EXIT WHEN C1%NOTFOUND;

    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_RETAILER_INFO_tab.first .. DM_RETAILER_INFO_tab.last
           INSERT INTO DM_RETAILER_INFO VALUES DM_RETAILER_INFO_tab(i);
                       

  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


