/********************************************************
*
* Name: DM_TRIP_HISTORY_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_TRIP_HISTORY_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_TRIP_HISTORY_INFO_PROC IS

TYPE DM_TRIP_HISTORY_INFO_TYP IS TABLE OF DM_TRIP_HISTORY_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_TRIP_HISTORY_INFO_tab DM_TRIP_HISTORY_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL APD_ID
    ,NULL TRIP_START_DATE
    ,NULL TRIP_END_DATE
    ,NULL RECON_DATE
    ,NULL TRIPS_MADE
    ,NULL TRIPS_CHARGED
    ,NULL LATE_TRIPS
    ,NULL AMOUNT_CHARGED
    ,NULL RECON_FLAG
    ,NULL TRIPS_LEFT
    ,NULL UPDATE_TS
    ,NULL LAST_TX_DATE
    ,NULL USAGE_AMOUNT
    ,NULL FULL_FARE_AMOUNT
    ,NULL DISCOUNTED_AMOUNT
    ,NULL ETC_ACCOUNT_ID
    ,NULL PLAN_TYPE
    ,NULL LAST_LANE_TX_ID
    ,NULL LAST_TX_POST_TIMESTAMP
    ,NULL COMPOSITE_TRANSACTION_ID
    ,NULL SOURCE_SYSTEM
    ,NULL TRANSPONDER_ID
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_TRIP_HISTORY_INFO_tab
    LIMIT P_ARRAY_SIZE;
    EXIT WHEN C1%NOTFOUND;

    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_TRIP_HISTORY_INFO_tab.first .. DM_TRIP_HISTORY_INFO_tab.last
           INSERT INTO DM_TRIP_HISTORY_INFO VALUES DM_TRIP_HISTORY_INFO_tab(i);
                       

  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


