/********************************************************
*
* Name: DM_ACCOUNT_HST_INFO_PROC
* Created by: DT, 5/27/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_ACCOUNT_HST_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_ACCOUNT_HST_INFO_PROC IS

TYPE DM_ACCOUNT_HST_INFO_TYP IS TABLE OF DM_ACCOUNT_HST_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_ACCOUNT_HST_INFO_tab DM_ACCOUNT_HST_INFO_TYP;

P_ARRAY_SIZE NUMBER:=10000;

CURSOR C1 IS SELECT 
    pa.ACCT_NUM ACCOUNT_NUMBER
    ,pa.ACCTSTAT_ACCT_STATUS_CODE ACCOUNT_STATUS
    ,NULL ACCOUNT_STATUS_DATETIME -- MAX(STATUS_CHG_DATE) PA_ACCT_STATUS_CHANGES
    ,'MAIL' STATEMENT_DELIVERY_MODE
    ,'NONE' STATEMENT_PERIOD  -- What is the source for this?PA_ACCT.Statement_option MONTHLY
    ,pa.ACCTTYPE_ACCT_TYPE_CODE ACCOUNT_TYPE
    ,pa.CREATED_ON ACCOUNT_OPEN_DATE    -- ACCT_OPEN_DATE 
    ,trunc(pa.L_NAME)||', '||trunc(pa.F_NAME) ACCOUNT_NAME
    ,pa.ORG COMPANY_NAME
    ,NULL DBA -- N/A
    ,pa.E_MAIL_ADDR EMAIL_ADDRESS
--    ,PA_ACCT_REPL_DETAIL.REPLENISHMENT_AMT REBILL_AMOUNT
--    ,PA_ACCT_REPL_DETAIL.LOW_BAL_AMT REBILL_THRESHOLD
    ,pa.ACCT_PIN_NUMBER PIN
    ,NULL VIDEO_ACCT_STATUS -- N/A
    ,NULL SUSPENDED_DATE -- N/A
--    ,pa.CREATED_ON LAST_INVOICE_DATE --  ST_DOCUMENT_INFO - MAX(CREATED_ON)
    ,NULL LAST_INVOICE_DATE --  ST_DOCUMENT_INFO - MAX(CREATED_ON)
    ,pa.CLOSED_DATE ACCOUNT_CLOSE_DATE
    ,NULL CORRESPONDENCE_DEL_MODE
    ,'ENGLISH' LANGUAGE_PREFERENCE
    ,'OPT-OUT' MOBILE_ALERTS
    ,NULL CHALLENGE_QUESTION    --KS_CHALLENGE_QUESTION.QUESTION   KS_USER_CHALLENGE_RESPONSE?
    ,NULL CHALLENGE_ANSWER -- KS_USER_CHALLENGE_RESPONSE.ANSWER
    ,NULL IS_POSTPAID  -- Derived
    ,NULL IS_SURVEY_OPTED  -- N/A
    ,NULL ACC_LOCKED_DATETIME -- N/A
    ,NULL ACCOUNT_LOCKED -- N/A
    ,NULL NSF_LOCK_RELEASED_DT -- N/A
    ,NULL CHARGEBACK_RELEASED_DT -- N/A
    ,pad.BKTY_FILE_DATE BANKRUPTCY
    ,'N' COURT_FLAG
    ,NULL OUTBOUND_DAILER
    ,NULL DO_NOT_CALL
    ,NULL APPLICATION_NUMBER
    ,pad.CA_AGENCY_ID COLLECTION_AGENCY -- Derived based on the Account number
    ,NULL ACCOUNT_CLOSE_PEND_DT
    ,pad.DECEASED_DATE DECEASED
    ,pa.CREATED_ON CREATED   -- SYSDATE ??
    ,'SUNTOLL_CSC_ID' CREATED_BY  -- SUNTOLL_CSC_ID
    ,to_date('02-27-2017', 'MM-DD-YYYY') LAST_UPD
    ,'SUNTOLL_CSC_ID' LAST_UPD_BY    -- SUNTOLL_CSC_ID
    ,pa.MAIDEN_NAME MOTHERS_MAIDEN_NAME
    ,pa.EIN FEIN_NUMBER
    ,pad.IS_CAST CAST_ACCOUNT_FLAG
    ,pa.TAX_EXEMPT_ID TAX_EXEMPTION_ID  -- TAX_EXEMPTION_ID
    ,pa.TAX_EXEMPT_EXPIRE_DATE EXPIRATION_DATE
    ,pa.ANON_ACCT ANONYMOUS_ACCOUNT
    ,NULL SECONDARY_EMAIL_ADDRESS
    ,'SUNTOLL' SOURCE_SYSTEM

    ,NULL ACTIVITY_ID
    ,NULL X_VERSION
    ,NULL EMP_NUM
    ,NULL X_POSTPAIDSTATUS
    ,NULL X_POST_PAID_STS_INT_ID
    ,NULL X_ACT_OPEN_MODE
    ,NULL X_APPLICATION_RECEIPTDATETIME
    ,NULL X_BANKRUPTCY_FLG
    ,NULL X_BLOCK_END_DT
    ,NULL X_BLOCK_ESCALATION
    ,NULL X_BLOCK_START_DT
    ,NULL X_CCU_ENDDATE
    ,NULL X_CCU_STARTDATE
    ,NULL X_CLOSURE_REASON
    ,NULL X_COLLATERALTYPE
    ,NULL X_COLLECTION_STATUS
    ,NULL X_COMMENTS
    ,NULL X_COMMERCIAL_AXLE_COUNT
    ,NULL X_DEVICEESTIMATEDCOLLATERAL
    ,NULL X_EXCLUDECOLLECTION
    ,NULL X_EXCLUDEREVOCATION
    ,NULL X_INVOICECYCLESTARTDATE
    ,NULL X_INVOICEDELIVERYFREQUENCYMODE
    ,NULL X_INVOICE_DELIVERY_MODE
    ,NULL X_ISDEVICEDEPOSIT
    ,NULL X_MARKETINGCODE
    ,NULL X_PAY_PLAN_FLG
    ,NULL X_PRIMARYORGANIZATION_ID
    ,NULL X_PRIMARY_ADDRESS_ID
    ,NULL X_PRIMARY_CONTACT_ID
    ,NULL X_PRIMARY_REBILL_ID
    ,NULL X_REPLENISHMENTCUSTOMERAMOUNT
    ,NULL X_REPLENISHMENTQEVALAMOUNT
    ,NULL X_REPLENISHMENTTHRESHOLDAMOUNT
    ,NULL X_REVOCATIONFINALBALANCE
    ,NULL X_SPEED_STATUS_ID
    ,NULL X_SWAPRETURNFEEEXCEMPT
    ,NULL X_TAXEXEMPT
    ,NULL X_TAXILEMO
    ,NULL X_TAXILIMOASSOCIATIONNAME
    ,NULL X_THRUWAY_REF_NUMBER
FROM PATRON.PA_ACCT pa
    ,PATRON.PA_ACCT_DETAIL pad
--    ,PATRON.KS_CHALLENGE_QUESTION
WHERE PA_ACCT.ACCT_NUM = PA_ACCT_DETAIL.ACCT_NUM --(+)
;
/*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_ACCOUNT_HST_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_ACCOUNT_HST_INFO_tab.first .. DM_ACCOUNT_HST_INFO_tab.last
           INSERT INTO DM_ACCOUNT_HST_INFO VALUES DM_ACCOUNT_HST_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


