/********************************************************
*
* Name: DM_ACCOUNT_TOLL_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_ACCOUNT_TOLL_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_ACCOUNT_TOLL_INFO_PROC IS

TYPE DM_ACCOUNT_TOLL_INFO_TYP IS TABLE OF DM_ACCOUNT_TOLL_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_ACCOUNT_TOLL_INFO_tab DM_ACCOUNT_TOLL_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;

-- EXTRACT RULE = SELECT * FROM PA_LANE_TXN WHERE TRANSPONDER_ID ENDS WITH '2010'  
/* indicates a violation toll */ -- (rentals included) 

CURSOR C1 IS SELECT 
    NULL TX_EXTERN_REF_NO -- JOIN TO TXN_ID OF PA_LANE_TXN RETURN HOST TO UFM_TOKEN
    ,EXT_MSG_SEQ_NUM TX_SEQ_NUMBER
    ,TOUR_TOUR_SEQ EXTERN_FILE_ID
    ,EXT_LANE_ID LANE_ID
    ,EXT_DATE_TIME TX_TIMESTAMP
    ,CASE WHEN MSG_ID IN ('TCA','XADJ','FADJ') 
          THEN 1 ELSE 0
      END TX_MOD_SEQ   -- IF MSG_ID IN ('TCA','XADJ','FADJ') THEN 1 ELSE 0
    ,'V' TX_TYPE_IND
    ,'I' TX_SUBTYPE_IND
    ,DECODE(substr(PLAZA_ID,1,3),'004', 'C', 'B')
        TOLL_SYSTEM_TYPE -- IF PLAZA_ID STARTS WITH '004' THEN 'C' ELSE 'B'
    ,EXT_LANE_TYPE_CODE LANE_MODE
    ,1 LANE_TYPE
    ,0 LANE_STATE
    ,0 LANE_HEALTH
    ,NULL PLAZA_AGENCY_ID -- Join ST_INTEROP_AGENCIES and PA_PLAZA on ENT_PLAZA_ID to PLAZA_ID
    ,EXT_PLAZA_ID PLAZA_ID
    ,0 COLLECTOR_ID
    ,0 TOUR_SEGMENT_ID
    ,0 ENTRY_DATA_SOURCE
    ,ENT_LANE_ID ENTRY_LANE_ID
    ,ENT_PLAZA_ID ENTRY_PLAZA_ID
    ,ENT_DATE_TIME ENTRY_TIMESTAMP
    ,TXN_ENTRY_NUMBER ENTRY_TX_SEQ_NUMBER
    ,0 ENTRY_VEHICLE_SPEED
    ,0 LANE_TX_STATUS
    ,0 LANE_TX_TYPE
    ,0 TOLL_REVENUE_TYPE
    ,AVC_CLASS ACTUAL_CLASS
    ,AVC_CLASS ACTUAL_AXLES
    ,0 ACTUAL_EXTRA_AXLES
    ,0 COLLECTOR_CLASS
    ,0 COLLECTOR_AXLES
    ,0 PRECLASS_CLASS
    ,0 PRECLASS_AXLES
    ,0 POSTCLASS_CLASS
    ,0 POSTCLASS_AXLES
    ,0 FORWARD_AXLES
    ,0 REVERSE_AXLES
    ,TOLL_AMT_FULL FULL_FARE_AMOUNT
    ,TOLL_AMT_CHARGED DISCOUNTED_AMOUNT
    ,TOLL_AMT_COLLECTED COLLECTED_AMOUNT
    ,0 UNREALIZED_AMOUNT
    ,'N' IS_DISCOUNTABLE
    ,'N' IS_MEDIAN_FARE
    ,'N' IS_PEAK
    ,0 PRICE_SCHEDULE_ID
    ,0 VEHICLE_SPEED
    ,0 RECEIPT_ISSUED
    ,TRANSP_ID DEVICE_NO
    ,ACCTTYPE_ACCT_TYPE_CODE ACCOUNT_TYPE -- PA_ACCT
    ,to_number(TRANSP_CLASS) DEVICE_CODED_CLASS  -- Convert to Number from varchar
    ,0 DEVICE_AGENCY_CLASS
    ,0 DEVICE_IAG_CLASS
    ,0 DEVICE_AXLES
    ,ACCT_NUM ETC_ACCOUNT_ID  -- KS_LEDGER - Join KS_LEDGER on TXN_ID
    ,0 ACCOUNT_AGENCY_ID
    ,'N' READ_AVI_CLASS
    ,'N' READ_AVI_AXLES
    ,0 DEVICE_PROGRAM_STATUS
    ,0 BUFFERED_READ_FLAG
    ,NVL(MSG_INVALID,0) LANE_DEVICE_STATUS
    ,0 POST_DEVICE_STATUS
    ,NULL PRE_TXN_BALANCE -- Derived - KS_LEDGER current balance minus amount 
-- PLAN_TYPE_ID - IF ITOL_AGENCY_CODE IN (9,10,11,12,13,14,15) 
-- THEN RENTAL ELSE POSTPAID, Xerox will provide numbers for  rental vs postpaid
    ,CASE WHEN ITOL_AGENCY_CODE IN (9,10,11,12,13,14,15) 
          THEN 'RENTAL' ELSE 'POSTPAID'
      END PLAN_TYPE_ID
    ,NULL ETC_TX_STATUS -- IF RENTAL THEN 9 of POSTPAID THEN 10 (From Above)
    ,'F' SPEED_VIOL_FLAG
    ,'Y' IMAGE_TAKEN
-- PLATE_COUNTRY - LOOKUP PA_STATE_CODE.  (visit DM_VEHICLE_INFO and DM_ACCT_INFO)
-- Xerox - internal lookup in DM_ADDRESS_INFO and assign country correctly. 
    ,NULL PLATE_COUNTRY -- - LOOKUP PA_STATE_CODE. 
    ,STATE_ID_CODE PLATE_STATE
    ,VEH_LIC_NUM PLATE_NUMBER
    ,trunc(EXT_DATE_TIME) REVENUE_DATE -- Date only
    ,trunc(TXN_PROCESS_DATE) POSTED_DATE -- Date only
    ,0 ATP_FILE_ID
    ,TXN_PROCESS_DATE UPDATE_TS -- Date and Time
    ,'N' IS_REVERSED
    ,0 CORR_REASON_ID
    ,trunc(TXN_PROCESS_DATE) RECON_DATE -- Date only
    ,NULL RECON_STATUS_IND  -- XEROX - TO FOLLOW UP
    ,NULL RECON_SUB_CODE_IND  -- XEROX - TO FOLLOW UP
    ,pt.COLLECTION_DATE EXTERN_FILE_DATE -- JOIN TO PA_TOUR ON TOUR_SEQ=TOUR_TOUR_SEQ RETURN COLLECTION_DATE
    ,0 MILEAGE
    ,0 DEVICE_READ_COUNT
    ,0 DEVICE_WRITE_COUNT
    ,0 ENTRY_DEVICE_READ_COUNT
    ,0 ENTRY_DEVICE_WRITE_COUNT
    ,'000000000000' DEPOSIT_ID
    ,EXT_DATE_TIME TX_DATE -- Date only
    ,p.PLAZA_NAME LOCATION  -- JOIN PA_PLAZA ON PLAZA_ID=EXT_PLAZA_ID RETURN PLAZA_NAME
    ,p.FACCODE_FACILITY_CODE FACILITY_ID -- JOIN PA_PLAZA ON PLAZA_ID=EXT_PLAZA_ID RETURN FACCODE_FACILITY_CODE
    ,0 FARE_TBL_ID
    ,0 TRAN_CODE
    ,'SUNTOLL' SOURCE_SYSTEM
    ,TXN_ID LANE_TX_ID
FROM PA_LANE_TXN plt
    ,PA_PLAZA pp
    ,PA_TOUR pt
WHERE lt.EXT_PLAZA_ID = pp.PLAZA_ID (+)
AND lt.TOUR_TOUR_SEQ = pt.TOUR_SEQ (+)
--WHERE TRANSPONDER_ID ENDS WITH '2010' 
; -- Source

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_ACCOUNT_TOLL_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_ACCOUNT_TOLL_INFO_tab.first .. DM_ACCOUNT_TOLL_INFO_tab.last
           INSERT INTO DM_ACCOUNT_TOLL_INFO VALUES DM_ACCOUNT_TOLL_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


