/********************************************************
*
* Name: DM_PA_PLAZA_INFO_PROC
* Created by: RH, 6/5/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_PA_PLAZA_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

--declare
CREATE OR REPLACE PROCEDURE DM_PA_PLAZA_INFO_PROC IS

TYPE DM_PA_PLAZA_INFO_TYP IS TABLE OF DM_PA_PLAZA_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_PA_PLAZA_INFO_tab DM_PA_PLAZA_INFO_TYP;

P_ARRAY_SIZE NUMBER:=10000;

CURSOR C1 IS SELECT 
    ADMINTYPE_ADMIN_TYPE_CODE
    ,AUTHCODE_AUTHORITY_CODE
    ,AVC_THRESHOLD
    ,CLASS2_RATE_FLAG
    ,COUNTY_COUNTY_CODE
    ,CROSS_READ_PLAZA_ID
    ,FACCODE_FACILITY_CODE
    ,FTE_PLAZA
    ,GEOG_COORD_LAT
    ,GEOG_COORD_LONG
    ,IAG_PLAZA_ID
    ,IN_LANE_DISC_PERCENT
    ,I_TOLL_PARTICIPATION
    ,MILE_POST
    ,MIN_FARE_PLAZA_ID
    ,N_BOUND_TIME
    ,PLAZA_ID
    ,PLAZA_NAME
    ,PLAZA_SHORT_NAME
    ,PLAZA_SLAVE_NUM
    ,RAMPTYPE_RAMP_TYPE_CODE
    ,REBATE_REBATE_PROGRAM_CODE
    ,REGCODE_REGION_CODE
    ,S_BOUND_TIME
    ,THRESHOLD
    ,TOLL_INEQUITY_PROGRAM_FLAG
    ,TRIP_PLAZA
    ,TRUSTEE_TRUSTEE_ID
    ,UTURN_INTERVAL
    ,VBTOL_EFFECTIVE_DATE
    ,VR_TOLL_PARTICIPATION
    ,'SUNTOLL' SOURCE_SYSTEM
FROM PA_PLAZA; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_PA_PLAZA_INFO_tab
    LIMIT P_ARRAY_SIZE;

    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_PA_PLAZA_INFO_tab.first .. DM_PA_PLAZA_INFO_tab.last
           INSERT INTO DM_PA_PLAZA_INFO VALUES DM_PA_PLAZA_INFO_tab(i);              

    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


