/********************************************************
*
* Name: DM_ACCOUNT_HST_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_ACCOUNT_HST_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_ACCOUNT_HST_INFO_PROC IS

TYPE DM_ACCOUNT_HST_INFO_TYP IS TABLE OF DM_ACCOUNT_HST_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_ACCOUNT_HST_INFO_tab DM_ACCOUNT_HST_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL ACCOUNT_NUMBER
    ,NULL ACCOUNT_STATUS
    ,NULL ACCOUNT_STATUS_DATETIME
    ,NULL STATEMENT_DELIVERY_MODE
    ,NULL STATEMENT_PERIOD
    ,NULL ACCOUNT_TYPE
    ,NULL ACCOUNT_OPEN_DATE
    ,NULL ACCOUNT_NAME
    ,NULL COMPANY_NAME
    ,NULL DBA
    ,NULL EMAIL_ADDRESS
    ,NULL REBILL_AMOUNT
    ,NULL REBILL_THRESHOLD
    ,NULL PIN
    ,NULL VIDEO_ACCT_STATUS
    ,NULL SUSPENDED_DATE
    ,NULL LAST_INVOICE_DATE
    ,NULL ACCOUNT_CLOSE_DATE
    ,NULL CORRESPONDENCE_DEL_MODE
    ,NULL LANGUAGE_PREFERENCE
    ,NULL MOBILE_ALERTS
    ,NULL CHALLENGE_QUESTION
    ,NULL CHALLENGE_ANSWER
    ,NULL IS_POSTPAID
    ,NULL IS_SURVEY_OPTED
    ,NULL ACC_LOCKED_DATETIME
    ,NULL ACCOUNT_LOCKED
    ,NULL NSF_LOCK_RELEASED_DT
    ,NULL CHARGEBACK_RELEASED_DT
    ,NULL BANKRUPTCY
    ,NULL COURT_FLAG
    ,NULL OUTBOUND_DAILER
    ,NULL DO_NOT_CALL
    ,NULL APPLICATION_NUMBER
    ,NULL COLLECTION_AGENCY
    ,NULL ACCOUNT_CLOSE_PEND_DT
    ,NULL DECEASED
    ,NULL CREATED
    ,NULL CREATED_BY
    ,NULL LAST_UPD
    ,NULL LAST_UPD_BY
    ,NULL MOTHERS_MAIDEN_NAME
    ,NULL FEIN_NUMBER
    ,NULL CAST_ACCOUNT_FLAG
    ,NULL TAX_EXEMPTION_ID
    ,NULL EXPIRATION_DATE
    ,NULL ANONYMOUS_ACCOUNT
    ,NULL SECONDARY_EMAIL_ADDRESS
    ,NULL SOURCE_SYSTEM
    ,NULL ACTIVITY_ID
    ,NULL X_VERSION
    ,NULL EMP_NUM
    ,NULL X_POSTPAIDSTATUS
    ,NULL X_POST_PAID_STS_INT_ID
    ,NULL X_ACT_OPEN_MODE
    ,NULL X_APPLICATION_RECEIPTDATETIME
    ,NULL X_BANKRUPTCY_FLG
    ,NULL X_BLOCK_END_DT
    ,NULL X_BLOCK_ESCALATION
    ,NULL X_BLOCK_START_DT
    ,NULL X_CCU_ENDDATE
    ,NULL X_CCU_STARTDATE
    ,NULL X_CLOSURE_REASON
    ,NULL X_COLLATERALTYPE
    ,NULL X_COLLECTION_STATUS
    ,NULL X_COMMENTS
    ,NULL X_COMMERCIAL_AXLE_COUNT
    ,NULL X_DEVICEESTIMATEDCOLLATERAL
    ,NULL X_EXCLUDECOLLECTION
    ,NULL X_EXCLUDEREVOCATION
    ,NULL X_INVOICECYCLESTARTDATE
    ,NULL X_INVOICEDELIVERYFREQUENCYMODE
    ,NULL X_INVOICE_DELIVERY_MODE
    ,NULL X_ISDEVICEDEPOSIT
    ,NULL X_MARKETINGCODE
    ,NULL X_PAY_PLAN_FLG
    ,NULL X_PRIMARYORGANIZATION_ID
    ,NULL X_PRIMARY_ADDRESS_ID
    ,NULL X_PRIMARY_CONTACT_ID
    ,NULL X_PRIMARY_REBILL_ID
    ,NULL X_REPLENISHMENTCUSTOMERAMOUNT
    ,NULL X_REPLENISHMENTQEVALAMOUNT
    ,NULL X_REPLENISHMENTTHRESHOLDAMOUNT
    ,NULL X_REVOCATIONFINALBALANCE
    ,NULL X_SPEED_STATUS_ID
    ,NULL X_SWAPRETURNFEEEXCEMPT
    ,NULL X_TAXEXEMPT
    ,NULL X_TAXILEMO
    ,NULL X_TAXILIMOASSOCIATIONNAME
    ,NULL X_THRUWAY_REF_NUMBER
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_ACCOUNT_HST_INFO_tab
    LIMIT P_ARRAY_SIZE;
    EXIT WHEN C1%NOTFOUND;

    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_ACCOUNT_HST_INFO_tab.first .. DM_ACCOUNT_HST_INFO_tab.last
           INSERT INTO DM_ACCOUNT_HST_INFO VALUES DM_ACCOUNT_HST_INFO_tab(i);
                       

  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


