/********************************************************
*
* Name: DM_DMV_INQUIRY_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_DMV_INQUIRY_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_DMV_INQUIRY_INFO_PROC IS

TYPE DM_DMV_INQUIRY_INFO_TYP IS TABLE OF DM_DMV_INQUIRY_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_DMV_INQUIRY_INFO_tab DM_DMV_INQUIRY_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL MODIFICATION_NUM
    ,NULL CONFLICT_ID
    ,NULL X_ETC_ACCOUNT_ID
    ,NULL X_HIST_FLG
    ,NULL X_ACCOUNT_ID
    ,NULL X_ADDR_LINE_1
    ,NULL X_ADDR_LINE_2
    ,NULL X_CITY
    ,NULL X_CONTACT_ID
    ,NULL X_COUNTRY
    ,NULL X_DMV_STATUS
    ,NULL X_FST_NAME
    ,NULL X_LAST_NAME
    ,NULL X_PLATE_NUM
    ,NULL X_SEND_DMV
    ,NULL X_STATE
    ,NULL X_STATUS
    ,NULL X_TOD_ID
    ,NULL X_ZIPCODE
    ,NULL CREATED
    ,NULL CREATED_BY
    ,NULL LAST_UPD
    ,NULL LAST_UPD_BY
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_DMV_INQUIRY_INFO_tab
    LIMIT P_ARRAY_SIZE;
    EXIT WHEN C1%NOTFOUND;

    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_DMV_INQUIRY_INFO_tab.first .. DM_DMV_INQUIRY_INFO_tab.last
           INSERT INTO DM_DMV_INQUIRY_INFO VALUES DM_DMV_INQUIRY_INFO_tab(i);
                       

  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


