/********************************************************
*
* Name: DM_TPMS_ACCOUNT_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_TPMS_ACCOUNT_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_TPMS_ACCOUNT_INFO_PROC IS

TYPE DM_TPMS_ACCOUNT_INFO_TYP IS TABLE OF DM_TPMS_ACCOUNT_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_TPMS_ACCOUNT_INFO_tab DM_TPMS_ACCOUNT_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL ETC_ACCOUNT_ID
    ,NULL AGENCY_ID
    ,NULL ACCOUNT_TYPE
    ,NULL CURRENT_BALANCE
    ,NULL POSTPAID_BALANCE
    ,NULL DEVICE_DEPOSIT
    ,NULL VIOL_PREPAYMENT
    ,NULL VIOL_OVERPAYMENT
    ,NULL IS_DISCOUNT_ELIGIBLE
    ,NULL LAST_TOLL_TX_ID
    ,NULL LAST_TOLL_POSTED_DATE
    ,NULL LAST_TOLL_TX_AMT
    ,NULL LAST_TOLL_TX_TIMESTAMP
    ,NULL FIRST_TOLL_TIMESTAMP
    ,NULL EVAL_START_DATE
    ,NULL EVAL_END_DATE
    ,NULL USAGE_AMOUNT
    ,NULL UPDATE_TS
    ,NULL OPEN_DATE
    ,NULL POSTPAID_UNBILLED_BALANCE
    ,NULL VIOL_TOLL_BALANCE
    ,NULL VIOL_FEE_BALANCE
    ,NULL VIOL_BALANCE
    ,NULL POSTPAID_FEE
    ,NULL COLL_TOLL
    ,NULL COLL_FEE
    ,NULL UTC_TOLL
    ,NULL UTC_FEE
    ,NULL COURT_TOLL
    ,NULL COURT_FEE
    ,NULL LAST_TOLL_TX_DATE
    ,NULL LAST_FIN_TX_DATE
    ,NULL ACCT_FIN_STATUS
    ,NULL LAST_PAYMENT_TX_ID
    ,NULL LAST_PAYMENT_DATE
    ,NULL LAST_FIN_TX_ID
    ,NULL LAST_FIN_TX_AMT
    ,NULL LAST_BAL_POS_DATE
    ,NULL LAST_BAL_NEG_DATE
    ,NULL LAST_VIOL_PAYMENT_DATE
    ,NULL POSTPAID_OVERPAYMENT
    ,NULL LAST_STMT_CLOSE_BALANCE
    ,NULL LAST_STMT_DATE
    ,NULL ACCOUNT_CCU
    ,NULL SOURCE_SYSTEM
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_TPMS_ACCOUNT_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_TPMS_ACCOUNT_INFO_tab.first .. DM_TPMS_ACCOUNT_INFO_tab.last
           INSERT INTO DM_TPMS_ACCOUNT_INFO VALUES DM_TPMS_ACCOUNT_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


