/********************************************************
*
* Name: DM_VIOL_TX_EVENT_INFO_PROC
* Created by: DT, 4/13/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_VIOL_TX_EVENT_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_VIOL_TX_EVENT_INFO_PROC IS

TYPE DM_VIOL_TX_EVENT_INFO_TYP IS TABLE OF DM_VIOL_TX_EVENT_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_VIOL_TX_EVENT_INFO_tab DM_VIOL_TX_EVENT_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    NULL EVENT_TYPE
    ,NULL PREV_EVENT_TYPE
    ,NULL VIOL_TX_STATUS
    ,NULL PREV_VIOL_TX_STATUS
    ,NULL EVENT_TIMESTAMP
    ,NULL ETC_ACCOUNT_ID
    ,NULL PLATE_NUMBER
    ,NULL PLATE_STATE
    ,NULL PLATE_COUNTRY
    ,NULL MAKE_ID
    ,NULL DMV_PLATE_TYPE
    ,NULL REVIEWED_VEHICLE_TYPE
    ,NULL REVIEWED_CLASS
    ,NULL VIOL_TYPE
    ,NULL OUTPUT_FILE_ID
    ,NULL OUTPUT_FILE_TYPE
    ,NULL TX_TIMESTAMP
    ,NULL TX_DATE
    ,NULL CITATION_LEVEL
    ,NULL CITATION_STATUS
    ,NULL NOTICE_FEE_AMOUNT
    ,NULL AMOUNT_PAID
    ,NULL DISCOUNTED_AMOUNT
    ,NULL IMAGE_BATCH_ID
    ,NULL IMAGE_BATCH_SEQ_NUMBER
    ,NULL RECON_STATUS_IND
    ,NULL SOURCE_SYSTEM
FROM FTE_TABLE; /*Change FTE_TABLE to the actual table name*/

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_VIOL_TX_EVENT_INFO_tab
    LIMIT P_ARRAY_SIZE;
    EXIT WHEN C1%NOTFOUND;

    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_VIOL_TX_EVENT_INFO_tab.first .. DM_VIOL_TX_EVENT_INFO_tab.last
           INSERT INTO DM_VIOL_TX_EVENT_INFO VALUES DM_VIOL_TX_EVENT_INFO_tab(i);
                       

  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


