/********************************************************
*
* Name: DM_EXEMPT_PLAN_PROC
* Created by: DT, 4/31/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_EXEMPT_PLAN
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_EXEMPT_PLAN_PROC IS

TYPE DM_EXEMPT_PLAN_TYP IS TABLE OF DM_EXEMPT_PLAN%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_EXEMPT_PLAN_tab DM_EXEMPT_PLAN_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    PA_TRANSP_ACCT.TRANSP_ID ACCOUNT_NUMBER
    ,EXEMPTIONS.EXEMPT_TYPE PLAN_NAME
    ,EXEMPTIONS.TRANSPONDER_ID DEVICE_NUMBER
    ,EXEMPTIONS.FROMDATE START_DATE
    ,EXEMPTIONS.TODATE END_DATE
    ,'PAID' PLAN_STATUS
    ,'N' AUTO_RENEW
    ,EXEMPTIONS.FROMDATE CREATED
    ,'000000' CREATED_BY
    ,EXEMPTIONS.FROMDATE LAST_UPD
    ,'000000' LAST_UPD_BY
    ,'SUNPASS' SOURCE_SYSTEM
    ,EXEMPTIONS.JURISDICTION PLATE_STATE
    ,PA_STATE_CODE PLATE_COUNTRY
    ,EXEMPTIONS.PLATE PLATE_NUMBER
FROM PA_TRANSP_ACCT;

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_EXEMPT_PLAN_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN */

    /*ETL SECTION END   */

    /*Bulk insert */ 
    FORALL i in DM_EXEMPT_PLAN_tab.first .. DM_EXEMPT_PLAN_tab.last
           INSERT INTO DM_EXEMPT_PLAN VALUES DM_EXEMPT_PLAN_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


