/********************************************************
*
* Name: DM_VEHICLE_INFO_PROC
* Created by: RH, 5/18/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_VEHICLE_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_VEHICLE_INFO_PROC IS

TYPE DM_VEHICLE_INFO_TYP IS TABLE OF DM_VEHICLE_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_VEHICLE_INFO_tab DM_VEHICLE_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    pav.ACCT_ACCT_NUM ACCOUNT_NUMBER
    ,DECODE(pav.VEH_LIC_NUM, 'O', '0', pav.VEH_LIC_NUM) PLATE_NUMBER  -- PATRON.EVENT_LOOKUP_ROV
    ,pav.STATE_STATE_CODE_ABBR PLATE_STATE
    ,'USA' PLATE_COUNTRY
    ,pav.VEH_LIC_TYPE PLATE_TYPE    -- Prefix and Suffix for the Country and State.  
    ,'REGULAR' VEHICLE_TYPE     
    ,SUBSCRIPTION_START_DATE EFFECTIVE_START_DATE
    ,SUBSCRIPTION_END_DATE EFFECTIVE_END_DATE
    ,nvl(trim(pav.VEH_MODEL_YR), '9999') YEAR
    ,nvl(trim(pav.VEH_MAKE), 'OTHER') MAKE
    ,nvl(trim(pav.VEH_MODEL), 'OTHER') MODEL
    ,trim(pav.VEH_COLOR) COLOUR
    ,srs.REG_STOP_SENT_ON REG_STOP_START_DATE  -- ST_REG_STOP
    ,srs.REG_STOP_REMOVAL_SENT_ON REG_STOP_END_DATE -- ST_REG_STOP
    ,NULL METAL_OXIDE_WIND_SHIELD
    ,NULL DMV_RETURN_DATE  -- suntoll    --MAX(RESPONSE_DATE)Event lookup ROV
    ,NULL VEHICLE_CLASS
    ,NULL AXLE_COUNT
    ,NULL IS_DUAL_TIRE
    ,pav.RENTAL_CAR_FLAG IS_RENTAL
    ,NULL RENTAL_COMPANY
    ,NULL RENTAL_COMPANY_PHONE
    ,pav.SUBSCRIPTION_START_DATE CREATED
    ,pav.EMP_EMP_CODE CREATED_BY
    ,pav.LAST_MODIFIED_DATE LAST_UPD
    ,'SUNTOLL_CSC_ID' LAST_UPD_BY   --	DEFAULT	SUNPASS_CSC_ID		LAST_UPD_BY	SUNPASS_CSC_ID (Default)
    ,pav.VEHICLE_SEQ VEHICLE_SEQUENCE
    ,'SUNTOLL' SOURCE_SYSTEM
    ,ev.PLATE_ISSUE_DATE PLATE_ISSUE_DATE    -- DERIVE  PLATE_ISSUE_DATE
    ,ev.REG_EXP_DATE PLATE_EXPIRY_DATE   -- DERIVE  REG_EXP_DATE
    ,ev.DECAL_ISSUE_DATE PLATE_RENEWAL_DATE  -- DERIVE  DECAL_ISSUE_DATE
    ,ev.VIN ALT_VEHICLE_ID      -- DERIVE  VIN
FROM PATRON.PA_ACCT_VEHICLE pav
    ,PATRON.ST_REG_STOP srs
    ,PATRON.EVENT_VEHICLE ev
WHERE pav.VEH_LIC_NUM = srs.VEH_LIC_NUM (+)
AND   pav.VEH_LIC_NUM = ev.PLATE (+)
; -- FTE source


BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_VEHICLE_INFO_tab
    LIMIT P_ARRAY_SIZE;
    -- PATRON.EVENT_LOOKUP_ROV

--ETL SECTION BEGIN mapping
    FOR i IN 1 .. DM_ACCOUNT_INFO_tab.COUNT LOOP
     
      select max(elr.RESPONSE_DATE) into  DM_ACCOUNT_INFO_tab(i).DMV_RETURN_DATE
      from PATRON.EVENT_LOOKUP_ROV elr
      where elr.PLATE = DM_ACCOUNT_INFO_tab(i).PLATE_NUMBER
      ;

    END LOOP;
--      ETL SECTION END

    /*Bulk insert */ 
    FORALL i in DM_VEHICLE_INFO_tab.first .. DM_VEHICLE_INFO_tab.last
           INSERT INTO DM_VEHICLE_INFO VALUES DM_VEHICLE_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


