/********************************************************
*
* Name: DM_VEHICLE_HST_INFO_PROC
* Created by: RH, 6/2/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_VEHICLE_HST_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

declare
--CREATE OR REPLACE PROCEDURE DM_VEHICLE_HST_INFO_PROC IS

TYPE DM_VEHICLE_HST_INFO_TYP IS TABLE OF DM_VEHICLE_HST_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_VEHICLE_HST_INFO_tab DM_VEHICLE_HST_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    pav.ACCT_ACCT_NUM ACCOUNT_NUMBER
    ,DECODE(pav.VEH_LIC_NUM, 'O', '0', pav.VEH_LIC_NUM) PLATE_NUMBER  -- PATRON.EVENT_LOOKUP_ROV
    ,pav.STATE_STATE_CODE_ABBR PLATE_STATE
    ,(select nvl(cs.COUNTRY,'USA') from  COUNTRY_STATE_LOOKUP cs
        where cs.STATE_ABBR = pav.STATE_STATE_CODE_ABBR) PLATE_COUNTRY
    ,pav.VEH_LIC_TYPE PLATE_TYPE    -- Prefix and Suffix for the Country and State.  
    ,'REGULAR' VEHICLE_TYPE     
    ,SUBSCRIPTION_START_DATE EFFECTIVE_START_DATE
    ,SUBSCRIPTION_END_DATE EFFECTIVE_END_DATE
    ,nvl(pav.VEH_MODEL_YR, '9999') YEAR
    ,nvl(pav.VEH_MAKE, 'OTHER') MAKE
    ,nvl(pav.VEH_MODEL, 'OTHER') MODEL
    ,pav.VEH_COLOR COLOUR
    ,srs.REG_STOP_SENT_ON REG_STOP_START_DATE  -- ST_REG_STOP
    ,srs.REG_STOP_REMOVAL_SENT_ON REG_STOP_END_DATE -- ST_REG_STOP
    ,NULL METAL_OXIDE_WIND_SHIELD
    ,NULL DMV_RETURN_DATE -- suntoll    --MAX(RESPONSE_DATE)Event lookup ROV
    ,NULL VEHICLE_CLASS
    ,NULL AXLE_COUNT
    ,NULL IS_DUAL_TIRE
    ,NULL IS_RENTAL
    ,pav.RENTAL_CAR_FLAG IS_RENTAL
    ,NULL RENTAL_COMPANY_PHONE
    ,pav.SUBSCRIPTION_START_DATE CREATED
    ,pav.EMP_EMP_CODE CREATED_BY
    ,pav.LAST_MODIFIED_DATE LAST_UPD
    ,NULL LAST_UPD_BY
    ,pav.VEHICLE_SEQ VEHICLE_SEQUENCE
    ,'SUNTOLL' SOURCE_SYSTEM
    ,NULL ACTIVITY_ID
    ,NULL REBILL_PAY_TYPE_INTEGRATION_ID
    ,NULL EMP_NUM
    ,NULL IS_MVA
    ,NULL X_LICENSE_STATUS
    ,NULL X_PLATE_VIN_NO
    ,NULL STATUS
    ,NULL X_ALTERNATEID
    ,NULL X_OWNER
    ,NULL X_WEB_VEHICLE_TYPE
FROM PATRON.PA_ACCT_VEHICLE pav
    ,PATRON.ST_REG_STOP srs
    ,PATRON.EVENT_VEHICLE ev
WHERE pav.VEH_LIC_NUM = srs.VEH_LIC_NUM (+)
AND   pav.VEH_LIC_NUM = ev.PLATE (+)
and rownum<11
; -- FTE source

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_VEHICLE_HST_INFO_tab
    LIMIT P_ARRAY_SIZE;

--ETL SECTION BEGIN mapping
    FOR i IN 1 .. DM_ACCOUNT_INFO_tab.COUNT LOOP
     
      select max(elr.RESPONSE_DATE) into  DM_ACCOUNT_INFO_tab(i).DMV_RETURN_DATE
      from PATRON.EVENT_LOOKUP_ROV elr
      where elr.PLATE = DM_ACCOUNT_INFO_tab(i).PLATE_NUMBER
      ;

    END LOOP;
--      ETL SECTION END

    /*Bulk insert */ 
    FORALL i in DM_VEHICLE_HST_INFO_tab.first .. DM_VEHICLE_HST_INFO_tab.last
           INSERT INTO DM_VEHICLE_HST_INFO VALUES DM_VEHICLE_HST_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


