/********************************************************
*
* Name: DM_VIOL_IMAGE_TX_INFO_PROC
* Created by: RH, 7/29/2016
* Revision: 1.0
* Description: This is the template for bulk read/write
*              DM_VIOL_IMAGE_TX_INFO
*
********************************************************/

set serveroutput on
set verify on
set echo on

CREATE OR REPLACE PROCEDURE DM_VIOL_IMAGE_TX_INFO_PROC IS

TYPE DM_VIOL_IMAGE_TX_INFO_TYP IS TABLE OF DM_VIOL_IMAGE_TX_INFO%ROWTYPE 
     INDEX BY BINARY_INTEGER;
DM_VIOL_IMAGE_TX_INFO_tab DM_VIOL_IMAGE_TX_INFO_TYP;


P_ARRAY_SIZE NUMBER:=10000;


CURSOR C1 IS SELECT 
    lt.EXT_LANE_ID LANE_ID
    ,lt.EXT_DATE_TIME TX_TIMESTAMP
    ,lt.EXT_MSG_SEQ_NUM TX_SEQ_NUMBER
    ,lt.VPS_EVENT_ID IN_FILE_NAME
    ,NULL OUT_FILE_NAME
    ,NULL PROCESS_DESC
    ,to_date(lt.EXT_DATE_TIME, 'MM/DD/YYYY') RECEIVE_DATE
    ,to_date(lt.EXT_DATE_TIME, 'MM/DD/YYYY') PROCESS_DATE
    ,NULL OCR_CONF
    ,NULL OCR_PLATE_STATE
    ,NULL OCR_PLATE_NUMBER
    ,lt.TXN_ID VEH_SEQ_NUMBER
    ,1 LANE_IMAGE_CNT
    ,0 PROC_IMAGE_CNT
    ,lt.EXT_DATE_TIME FTP_TIMESTAMP
    ,lt.EXT_DATE_TIME UPDATE_TS
    ,NULL OCR_STATUS
    ,to_date(lt.EXT_DATE_TIME, 'MM/DD/YYYY') TX_DATE
    ,lt.TXN_ID LANE_TX_ID
    ,NULL ZIP_FILE_NAME
    ,0 TR_FILE_ID
    ,0 RET_FILE_ID
    ,1 IMAGE_STATUS
    ,NULL AXLE_COUNT
    ,NULL IMAGE_TAKEN_REASON
    ,NULL PROCESS_FLAG
    ,2 IMP_TYPE
    ,lt.EXT_PLAZA_ID PLAZA_ID
    ,'MAN' MATCH_TYPE
    ,0 FP_CONF
    ,'C' COLOR_BW
    ,NULL OCR_PLATE_COUNTRY
    ,0 DMV_PLATE_TYPE
    ,0 IMAGE_TX_ID
    ,lt.EXT_PLAZA_ID REDUCED_PLATE
    ,NULL MANUAL_PLATE_NUMBER
    ,NULL MANUAL_PLATE_STATE
    ,0 MANUAL_PLATE_TYPE
    ,NULL MANUAL_PLATE_COUNTRY
    ,NULL IMAGE_RVW_CLERK_ID
    ,0 REVIEWED_VEHICLE_TYPE
    ,NULL IMAGE_REVIEW_TIMESTAMP
    ,NULL REVIEWED_DATE
    ,0 IMAGE_BATCH_ID
    ,0 IMAGE_BATCH_SEQ_NUMBER
    ,NULL DEVICE_NO
    ,lt.AVC_CLASS ACTUAL_AXLES
    ,lt.AVC_CLASS ACTUAL_CLASS
    ,0 READ_AVI_CLASS
    ,0 REVIEWED_CLASS
    ,0 POSTCLASS_AXLES
    ,0 FP_STATUS
    ,NULL OCR_THRESHOLD
    ,0 FP_THRESHOLD
    ,0 OCR_RUN_MODE
    ,lt.EXT_DATE_TIME OCR_START_TIMESTAMP
    ,lt.EXT_DATE_TIME OCR_END_TIMESTAMP
    ,1 IMG_FILE_INDEX
    ,'SUNTOLL' SOURCE_SYSTEM
FROM PA_LANE_TXN lt;

BEGIN
 
  OPEN C1;  

  LOOP

    /*Bulk select */
    FETCH C1 BULK COLLECT INTO DM_VIOL_IMAGE_TX_INFO_tab
    LIMIT P_ARRAY_SIZE;


    /*ETL SECTION BEGIN

      ETL SECTION END*/

    /*Bulk insert */ 
    FORALL i in DM_VIOL_IMAGE_TX_INFO_tab.first .. DM_VIOL_IMAGE_TX_INFO_tab.last
           INSERT INTO DM_VIOL_IMAGE_TX_INFO VALUES DM_VIOL_IMAGE_TX_INFO_tab(i);
                       
    EXIT WHEN C1%NOTFOUND;
  END LOOP;

  COMMIT;

  CLOSE C1;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('ERROR CODE: '||SQLCODE);
     DBMS_OUTPUT.PUT_LINE('ERROR MSG: '||SQLERRM);
END;
/
SHOW ERRORS


